from __future__ import annotations

import re
import argparse
from typing import Iterable

from sqlalchemy import MetaData, create_engine, text
from sqlalchemy.pool import NullPool

from yuantus.config import get_settings
from yuantus.database import tenant_id_to_schema
from yuantus.models.base import Base, WorkflowBase


GLOBAL_TABLE_NAMES = frozenset(
    {
        "audit_logs",
        "auth_credentials",
        "auth_org_memberships",
        "auth_organizations",
        "auth_tenant_quotas",
        "auth_tenants",
        "auth_users",
        "rbac_permissions",
        "rbac_resources",
        "rbac_role_permissions",
        "rbac_roles",
        "rbac_user_permissions",
        "rbac_user_roles",
        "rbac_users",
        "users",
    }
)

_TARGET_SCHEMA_RE = re.compile(r"^yt_t_[a-z0-9_]+$")
_PG_MAX_IDENTIFIER = 63


def register_tenant_model_metadata() -> None:
    """Import model modules needed by the tenant Alembic metadata filter.

    `import_all_models()` covers the bulk of the tenant model surface but
    historically misses a few `meta_engine.*` model packages that only get
    imported when their routers are loaded by `create_app()`. P3.3.3
    enumerates them explicitly so the tenant Alembic env's `target_metadata`
    matches what a fully-booted app sees, which keeps the baseline revision
    deterministic regardless of whether the test process happened to import
    `create_app()` first.
    """
    from yuantus.meta_engine.bootstrap import import_all_models

    import_all_models()

    # meta_engine model packages NOT covered by import_all_models() but loaded
    # by the runtime app via routers. Without these, build_tenant_metadata()
    # produces a smaller-than-runtime metadata set and the baseline revision
    # drifts depending on whether create_app() was imported earlier in the
    # process.
    from yuantus.meta_engine.box import models as _box  # noqa: F401
    from yuantus.meta_engine.cutted_parts import models as _cutted_parts  # noqa: F401
    from yuantus.meta_engine.document_sync import models as _document_sync  # noqa: F401
    from yuantus.meta_engine.locale import models as _locale  # noqa: F401
    from yuantus.meta_engine.maintenance import models as _maintenance  # noqa: F401
    from yuantus.meta_engine.quality import models as _quality  # noqa: F401
    from yuantus.meta_engine.report_locale import models as _report_locale  # noqa: F401

    # Global/control-plane tables are registered so the filter can exclude
    # them and tests can assert an exhaustive partition.
    from yuantus.models import audit as _audit  # noqa: F401
    from yuantus.models import user as _user  # noqa: F401
    from yuantus.security.rbac import models as _rbac_models  # noqa: F401


def _copy_tables(source: MetaData, target: MetaData, *, exclude: Iterable[str]) -> None:
    excluded = set(exclude)
    for name, table in source.tables.items():
        if name in excluded or name in target.tables:
            continue
        if hasattr(table, "to_metadata"):
            table.to_metadata(target)
        else:  # SQLAlchemy < 1.4 compatibility.
            table.tometadata(target)


def build_combined_metadata() -> MetaData:
    """Return Base + WorkflowBase metadata after all tenant-relevant imports."""
    register_tenant_model_metadata()
    combined = MetaData()
    _copy_tables(Base.metadata, combined, exclude=())
    _copy_tables(WorkflowBase.metadata, combined, exclude=())
    return combined


def build_tenant_metadata() -> MetaData:
    """Return metadata for per-tenant application tables only."""
    tenant_metadata = MetaData()
    register_tenant_model_metadata()
    _copy_tables(Base.metadata, tenant_metadata, exclude=GLOBAL_TABLE_NAMES)
    _copy_tables(WorkflowBase.metadata, tenant_metadata, exclude=GLOBAL_TABLE_NAMES)
    return tenant_metadata


def _validate_target_schema(value: str | None) -> str:
    """Validate an operator-supplied schema generated by tenant_id_to_schema()."""
    if value is None:
        raise ValueError("tenant Alembic target_schema is required")
    schema = str(value).strip()
    if not schema:
        raise ValueError("tenant Alembic target_schema is required")
    if len(schema) > _PG_MAX_IDENTIFIER:
        raise ValueError(
            f"tenant Alembic target_schema {schema!r} exceeds {_PG_MAX_IDENTIFIER} chars"
        )
    if not _TARGET_SCHEMA_RE.fullmatch(schema):
        raise ValueError(
            "tenant Alembic target_schema must match ^yt_t_[a-z0-9_]+$ "
            "and should be produced by tenant_id_to_schema()"
        )
    return schema


def _require_postgres_url(url: str) -> str:
    """Validate that the tenant migration plane is pointed at Postgres."""
    if not (url.startswith("postgresql") or url.startswith("postgres")):
        raise RuntimeError(
            "migrations_tenant/env.py requires a PostgreSQL DATABASE_URL; "
            f"got {url!r}"
        )
    return url


def resolve_schema_for_tenant_id(tenant_id: str) -> str:
    """Public helper used by operators to preview the managed schema name."""
    return tenant_id_to_schema(tenant_id)


def _quote_schema(schema: str) -> str:
    return f'"{_validate_target_schema(schema)}"'


def provision_tenant_schema(tenant_id: str, *, create: bool = True) -> str:
    """Resolve tenant_id to a managed schema and optionally create it."""
    settings = get_settings()
    schema = resolve_schema_for_tenant_id(tenant_id)
    if not create:
        return schema

    url = _require_postgres_url(settings.DATABASE_URL)
    engine = create_engine(url, poolclass=NullPool)
    try:
        with engine.begin() as connection:
            connection.execute(
                text(f"CREATE SCHEMA IF NOT EXISTS {_quote_schema(schema)}")
            )
    finally:
        engine.dispose()
    return schema


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m yuantus.scripts.tenant_schema",
        description="Resolve or provision a managed tenant schema.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    resolve_parser = subparsers.add_parser("resolve")
    resolve_parser.add_argument("--tenant-id", required=True)

    create_parser = subparsers.add_parser("create")
    create_parser.add_argument("--tenant-id", required=True)

    args = parser.parse_args(argv)
    if args.command == "resolve":
        print(resolve_schema_for_tenant_id(args.tenant_id))
        return 0
    if args.command == "create":
        print(provision_tenant_schema(args.tenant_id))
        return 0
    parser.error(f"unsupported command {args.command!r}")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
