from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

from yuantus.scripts import tenant_import_rehearsal_redaction_guard as redaction_guard
from yuantus.scripts.tenant_import_cli_safety import build_redacting_parser


SCHEMA_VERSION = "p3.4.2-tenant-import-rehearsal-synthetic-drill-v1"
_DEFAULT_PREFIX = "tenant_import_rehearsal_synthetic_drill"
_REDACTED_SYNTHETIC_URL = "postgresql://synthetic:***@example.invalid/rehearsal"
_PLAINTEXT_SYNTHETIC_URL = (
    "postgresql://synthetic:not-a-real-secret@example.invalid/rehearsal"
)


def _write_json(path: Path, report: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def _artifact_paths(*, artifact_dir: Path, artifact_prefix: str) -> dict[str, Path]:
    return {
        "synthetic_operator_evidence_md": (
            artifact_dir / f"{artifact_prefix}_operator_evidence.md"
        ),
        "synthetic_external_status_json": (
            artifact_dir / f"{artifact_prefix}_external_status.json"
        ),
        "synthetic_operator_notes_md": artifact_dir / f"{artifact_prefix}_notes.md",
        "redaction_guard_json": artifact_dir / f"{artifact_prefix}_redaction_guard.json",
        "redaction_guard_md": artifact_dir / f"{artifact_prefix}_redaction_guard.md",
    }


def _synthetic_external_status(url: str) -> dict[str, Any]:
    return {
        "schema_version": "synthetic-drill-only",
        "synthetic_drill": True,
        "real_rehearsal_evidence": False,
        "tenant_id": "synthetic-tenant",
        "target_schema": "yt_t_synthetic_tenant",
        "target_url": url,
        "current_stage": "synthetic_drill_only",
        "next_action": "run real operator rehearsal before evidence handoff",
        "ready_for_external_progress": False,
        "ready_for_operator_evidence": False,
        "ready_for_cutover": False,
        "blockers": [
            "synthetic drill artifacts are not operator-run PostgreSQL evidence",
        ],
    }


def _synthetic_operator_evidence_markdown(url: str) -> str:
    return "\n".join(
        [
            "# Synthetic Tenant Import Rehearsal Operator Evidence",
            "",
            "This file is generated by the DB-free synthetic drill.",
            "",
            "## Synthetic Sign-Off",
            "",
            "```text",
            "Pilot tenant: synthetic-tenant",
            f"Non-production rehearsal DB: {url}",
            "Backup/restore owner: synthetic-owner",
            "Rehearsal window: synthetic-window",
            "Rehearsal executed by: synthetic-operator",
            "Rehearsal result: synthetic-only",
            "Evidence reviewer: synthetic-reviewer",
            "Date: 2026-04-29",
            "```",
            "",
            "## Boundary",
            "",
            "- Synthetic drill: `true`",
            "- Real rehearsal evidence: `false`",
            "- Ready for cutover: `false`",
            "",
        ]
    )


def _synthetic_notes_markdown() -> str:
    return "\n".join(
        [
            "# Tenant Import Rehearsal Synthetic Drill Notes",
            "",
            "- Synthetic drill: `true`",
            "- Real rehearsal evidence: `false`",
            "- Database connection attempted: `false`",
            "- Ready for evidence handoff: `false`",
            "- Ready for cutover: `false`",
            "",
            "Use this output only to verify local artifact and redaction tooling.",
            "",
        ]
    )


def _write_synthetic_artifacts(
    *,
    artifact_dir: Path,
    artifact_prefix: str,
    inject_plaintext_secret_for_test: bool,
) -> dict[str, Path]:
    paths = _artifact_paths(
        artifact_dir=artifact_dir,
        artifact_prefix=artifact_prefix,
    )
    url = (
        _PLAINTEXT_SYNTHETIC_URL
        if inject_plaintext_secret_for_test
        else _REDACTED_SYNTHETIC_URL
    )
    _write_text(
        paths["synthetic_operator_evidence_md"],
        _synthetic_operator_evidence_markdown(url),
    )
    _write_json(paths["synthetic_external_status_json"], _synthetic_external_status(url))
    _write_text(paths["synthetic_operator_notes_md"], _synthetic_notes_markdown())
    return paths


def _artifact_summary(paths: dict[str, Path]) -> list[dict[str, Any]]:
    summary: list[dict[str, Any]] = []
    for name, path in paths.items():
        if name.startswith("redaction_guard_"):
            continue
        summary.append(
            {
                "artifact": name,
                "path": str(path),
                "exists": path.is_file(),
                "bytes": path.stat().st_size if path.is_file() else 0,
                "synthetic_drill": True,
                "real_rehearsal_evidence": False,
            }
        )
    return summary


def build_synthetic_drill_report(
    *,
    artifact_dir: str | Path,
    artifact_prefix: str = _DEFAULT_PREFIX,
    inject_plaintext_secret_for_test: bool = False,
) -> dict[str, Any]:
    """Generate DB-free synthetic artifacts and prove redaction wiring works."""
    target_dir = Path(artifact_dir)
    paths = _write_synthetic_artifacts(
        artifact_dir=target_dir,
        artifact_prefix=artifact_prefix,
        inject_plaintext_secret_for_test=inject_plaintext_secret_for_test,
    )
    artifact_paths = [
        paths["synthetic_operator_evidence_md"],
        paths["synthetic_external_status_json"],
        paths["synthetic_operator_notes_md"],
    ]
    redaction_report = redaction_guard.build_redaction_guard_report(
        artifacts=artifact_paths,
    )
    _write_json(paths["redaction_guard_json"], redaction_report)
    _write_text(
        paths["redaction_guard_md"],
        redaction_guard.render_markdown_report(redaction_report),
    )
    blockers = list(redaction_report["blockers"])

    return {
        "schema_version": SCHEMA_VERSION,
        "artifact_dir": str(target_dir),
        "artifact_prefix": artifact_prefix,
        "synthetic_drill": True,
        "real_rehearsal_evidence": False,
        "db_connection_attempted": False,
        "ready_for_synthetic_drill": not blockers,
        "ready_for_operator_evidence": False,
        "ready_for_evidence_handoff": False,
        "ready_for_cutover": False,
        "redaction_guard_json": str(paths["redaction_guard_json"]),
        "redaction_guard_ready": redaction_report["ready_for_artifact_handoff"],
        "artifacts": _artifact_summary(paths),
        "non_evidence_reasons": [
            "synthetic drill does not open source or target databases",
            "synthetic drill does not run tenant row-copy rehearsal",
            "synthetic drill artifacts must not be attached as real operator evidence",
        ],
        "blockers": blockers,
    }


def render_markdown_report(report: dict[str, Any]) -> str:
    blockers = report["blockers"] or ["None"]
    reasons = report["non_evidence_reasons"] or ["None"]
    lines = [
        "# Tenant Import Rehearsal Synthetic Drill",
        "",
        f"- Schema version: `{report['schema_version']}`",
        f"- Synthetic drill: `{str(report['synthetic_drill']).lower()}`",
        f"- Real rehearsal evidence: `{str(report['real_rehearsal_evidence']).lower()}`",
        f"- DB connection attempted: `{str(report['db_connection_attempted']).lower()}`",
        f"- Ready for synthetic drill: `{str(report['ready_for_synthetic_drill']).lower()}`",
        f"- Ready for operator evidence: `{str(report['ready_for_operator_evidence']).lower()}`",
        f"- Ready for evidence handoff: `{str(report['ready_for_evidence_handoff']).lower()}`",
        f"- Ready for cutover: `{str(report['ready_for_cutover']).lower()}`",
        f"- Redaction guard JSON: `{report['redaction_guard_json']}`",
        "",
        "## This Is Not Evidence",
        "",
    ]
    lines.extend(f"- {reason}" for reason in reasons)
    lines.extend(["", "## Blockers", ""])
    lines.extend(f"- {blocker}" for blocker in blockers)
    lines.extend(
        [
            "",
            "## Synthetic Artifacts",
            "",
            "| Artifact | Exists | Bytes | Path |",
            "| --- | --- | ---: | --- |",
        ]
    )
    for item in report["artifacts"]:
        lines.append(
            "| "
            f"`{item['artifact']}` | "
            f"`{str(item['exists']).lower()}` | "
            f"{item['bytes']} | "
            f"`{item['path']}` |"
        )
    if not report["artifacts"]:
        lines.append("| None | `false` | 0 | `` |")
    lines.extend(
        [
            "",
            "## Scope",
            "",
            "This drill writes synthetic local files and runs the redaction guard "
            "against them. It does not open database connections, run row-copy, "
            "accept operator evidence, build an archive manifest, pass the "
            "evidence handoff gate, authorize production cutover, or enable "
            "runtime schema-per-tenant mode.",
            "",
        ]
    )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = build_redacting_parser(
        prog="python -m yuantus.scripts.tenant_import_rehearsal_synthetic_drill",
        description=(
            "Generate DB-free synthetic P3.4.2 artifacts to drill local "
            "redaction tooling without accepting real evidence."
        ),
    )
    parser.add_argument("--artifact-dir", required=True)
    parser.add_argument("--artifact-prefix", default=_DEFAULT_PREFIX)
    parser.add_argument("--output-json", required=True)
    parser.add_argument("--output-md", required=True)
    parser.add_argument(
        "--inject-plaintext-secret-for-test",
        action="store_true",
        help="Generate a failing synthetic artifact to exercise redaction failure paths.",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Exit 1 unless the synthetic drill and redaction scan are clean.",
    )
    args = parser.parse_args(argv)

    try:
        report = build_synthetic_drill_report(
            artifact_dir=args.artifact_dir,
            artifact_prefix=args.artifact_prefix,
            inject_plaintext_secret_for_test=args.inject_plaintext_secret_for_test,
        )
        _write_json(Path(args.output_json), report)
        _write_text(Path(args.output_md), render_markdown_report(report))
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    if args.strict and not report["ready_for_synthetic_drill"]:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
