"""initial schema

Revision ID: f87ce5711ce1
Revises: 
Create Date: 2025-12-18 23:11:47.158468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = 'f87ce5711ce1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tenants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_conversion_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_conversion_jobs_status'), 'meta_conversion_jobs', ['status'], unique=False)
    op.create_table('meta_eco_stages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('fold', sa.Boolean(), nullable=True),
    sa.Column('is_blocking', sa.Boolean(), nullable=True),
    sa.Column('approval_type', sa.String(length=20), nullable=True),
    sa.Column('approval_roles', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('min_approvals', sa.Integer(), nullable=True),
    sa.Column('auto_progress', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_extension_points',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('meta_forms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_grid_views',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_lifecycle_maps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_methods',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_permissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_vaults',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('storage_type', sa.String(), nullable=True),
    sa.Column('base_path', sa.String(), nullable=True),
    sa.Column('url_template', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_workflow_maps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rbac_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('resource_metadata', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['rbac_resources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rbac_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['rbac_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rbac_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auth_organizations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['auth_tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_tenant_org')
    )
    op.create_index(op.f('ix_auth_organizations_tenant_id'), 'auth_organizations', ['tenant_id'], unique=False)
    op.create_table('auth_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['auth_tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'username', name='uq_auth_user_tenant_username')
    )
    op.create_index(op.f('ix_auth_users_tenant_id'), 'auth_users', ['tenant_id'], unique=False)
    op.create_table('meta_access',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('permission_id', sa.String(), nullable=True),
    sa.Column('identity_id', sa.String(), nullable=True),
    sa.Column('can_create', sa.Boolean(), nullable=True),
    sa.Column('can_get', sa.Boolean(), nullable=True),
    sa.Column('can_update', sa.Boolean(), nullable=True),
    sa.Column('can_delete', sa.Boolean(), nullable=True),
    sa.Column('can_discover', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['meta_permissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_app_registry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('dependencies', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('installed_content', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.Column('installed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['installed_by_id'], ['rbac_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_app_name')
    )
    op.create_table('meta_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('vault_id', sa.String(), nullable=True),
    sa.Column('system_path', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('is_native_cad', sa.Boolean(), nullable=True),
    sa.Column('cad_format', sa.String(), nullable=True),
    sa.Column('preview_path', sa.String(), nullable=True),
    sa.Column('preview_data', sa.Text(), nullable=True),
    sa.Column('geometry_path', sa.String(), nullable=True),
    sa.Column('printout_path', sa.String(), nullable=True),
    sa.Column('conversion_status', sa.String(), nullable=True),
    sa.Column('conversion_error', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_file_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['rbac_users.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['meta_files.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['meta_vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_files_checksum'), 'meta_files', ['checksum'], unique=False)
    op.create_index(op.f('ix_meta_files_file_type'), 'meta_files', ['file_type'], unique=False)
    op.create_table('meta_form_fields',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('form_id', sa.String(), nullable=True),
    sa.Column('property_name', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('x_pos', sa.Integer(), nullable=True),
    sa.Column('y_pos', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('control_type', sa.String(), nullable=True),
    sa.Column('on_change_handler', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['meta_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_grid_columns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('grid_view_id', sa.String(), nullable=True),
    sa.Column('property_name', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grid_view_id'], ['meta_grid_views.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_item_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=True, comment='Stable UUID for ItemType'),
    sa.Column('is_relationship', sa.Boolean(), nullable=True),
    sa.Column('is_versionable', sa.Boolean(), nullable=True),
    sa.Column('version_control_enabled', sa.Boolean(), nullable=True),
    sa.Column('revision_scheme', sa.String(length=50), nullable=True, comment='Revisioning scheme (e.g., A-Z, 1.2.3)'),
    sa.Column('permission_id', sa.String(), nullable=True),
    sa.Column('lifecycle_map_id', sa.String(), nullable=True),
    sa.Column('properties_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True, comment='JSON Schema definition of properties'),
    sa.Column('ui_layout', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True, comment='UI layout configuration (Form, List, Search)'),
    sa.Column('methods', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True, comment='Server-side method definitions'),
    sa.Column('on_before_add_method_id', sa.String(), nullable=True),
    sa.Column('on_after_update_method_id', sa.String(), nullable=True),
    sa.Column('source_item_type_id', sa.String(), nullable=True),
    sa.Column('related_item_type_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lifecycle_map_id'], ['meta_lifecycle_maps.id'], ),
    sa.ForeignKeyConstraint(['related_item_type_id'], ['meta_item_types.id'], ),
    sa.ForeignKeyConstraint(['source_item_type_id'], ['meta_item_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_lifecycle_states',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lifecycle_map_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('is_start_state', sa.Boolean(), nullable=True),
    sa.Column('is_end_state', sa.Boolean(), nullable=True),
    sa.Column('is_released', sa.Boolean(), nullable=True),
    sa.Column('version_lock', sa.Boolean(), nullable=True),
    sa.Column('permission_id', sa.String(), nullable=True),
    sa.Column('default_permission_id', sa.String(), nullable=True, comment='进入此状态时Item获得的默认权限'),
    sa.Column('workflow_map_id', sa.String(), nullable=True, comment='进入此状态时自动触发的工作流'),
    sa.ForeignKeyConstraint(['default_permission_id'], ['meta_permissions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lifecycle_map_id'], ['meta_lifecycle_maps.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['meta_permissions.id'], ),
    sa.ForeignKeyConstraint(['workflow_map_id'], ['meta_workflow_maps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_relationship_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('source_item_type', sa.String(length=100), nullable=False, comment='源ItemType名称'),
    sa.Column('related_item_type', sa.String(length=100), nullable=False, comment='目标ItemType名称'),
    sa.Column('is_polymorphic', sa.Boolean(), nullable=False, comment='是否允许多态（related可以是子类型）'),
    sa.Column('cascade_delete', sa.Boolean(), nullable=False, comment='删除source时是否级联删除关系'),
    sa.Column('max_quantity', sa.Integer(), nullable=True, comment='最大关系数量，null表示无限'),
    sa.Column('property_definitions', sa.JSON(), nullable=True, comment='关系自身的属性定义'),
    sa.Column('lifecycle_map_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lifecycle_map_id'], ['meta_lifecycle_maps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('meta_workflow_activities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_map_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('is_voting', sa.Boolean(), nullable=True),
    sa.Column('assignee_type', sa.String(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dynamic_identity', sa.String(), nullable=True),
    sa.Column('ui_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['rbac_users.id'], ),
    sa.ForeignKeyConstraint(['workflow_map_id'], ['meta_workflow_maps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rbac_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['rbac_resources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rbac_user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['rbac_users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('auth_credentials',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('auth_org_memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['auth_organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['auth_tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'org_id', 'user_id', name='uq_auth_membership')
    )
    op.create_index(op.f('ix_auth_org_memberships_org_id'), 'auth_org_memberships', ['org_id'], unique=False)
    op.create_index(op.f('ix_auth_org_memberships_tenant_id'), 'auth_org_memberships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_auth_org_memberships_user_id'), 'auth_org_memberships', ['user_id'], unique=False)
    op.create_table('cad_conversion_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_file_id', sa.String(), nullable=False),
    sa.Column('target_format', sa.String(), nullable=False),
    sa.Column('operation_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_file_id', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['result_file_id'], ['meta_files.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['meta_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cad_conversion_jobs_status'), 'cad_conversion_jobs', ['status'], unique=False)
    op.create_table('meta_extensions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('point_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('handler', sa.String(length=200), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['meta_app_registry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['point_id'], ['meta_extension_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('item_type_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config_id', sa.String(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('current_state', sa.String(), nullable=True),
    sa.Column('is_versionable', sa.Boolean(), nullable=True),
    sa.Column('current_version_id', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('locked_by_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('related_id', sa.String(), nullable=True),
    sa.Column('properties', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['rbac_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_state'], ['meta_lifecycle_states.id'], ),
    sa.ForeignKeyConstraint(['current_version_id'], ['meta_item_versions.id'], name='fk_item_current_version', use_alter=True),
    sa.ForeignKeyConstraint(['item_type_id'], ['meta_item_types.id'], ),
    sa.ForeignKeyConstraint(['locked_by_id'], ['rbac_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modified_by_id'], ['rbac_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['rbac_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_id'], ['meta_items.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['meta_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_items_config_id'), 'meta_items', ['config_id'], unique=False)
    op.create_index(op.f('ix_meta_items_item_type_id'), 'meta_items', ['item_type_id'], unique=False)
    op.create_index(op.f('ix_meta_items_related_id'), 'meta_items', ['related_id'], unique=False)
    op.create_index(op.f('ix_meta_items_source_id'), 'meta_items', ['source_id'], unique=False)
    op.create_table('meta_lifecycle_transitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lifecycle_map_id', sa.String(), nullable=True),
    sa.Column('from_state_id', sa.String(), nullable=True),
    sa.Column('to_state_id', sa.String(), nullable=True),
    sa.Column('action_name', sa.String(length=50), nullable=True),
    sa.Column('role_allowed_id', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['from_state_id'], ['meta_lifecycle_states.id'], ),
    sa.ForeignKeyConstraint(['lifecycle_map_id'], ['meta_lifecycle_maps.id'], ),
    sa.ForeignKeyConstraint(['role_allowed_id'], ['rbac_roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_state_id'], ['meta_lifecycle_states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_properties',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('item_type_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('default_value', sa.String(), nullable=True),
    sa.Column('ui_type', sa.String(length=50), nullable=True, comment='Frontend UI widget type'),
    sa.Column('ui_options', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True, comment='Frontend UI widget options'),
    sa.Column('is_cad_synced', sa.Boolean(), nullable=True, comment='True if this property is synced from CAD data'),
    sa.Column('default_value_expression', sa.Text(), nullable=True, comment='Expression for dynamic default value'),
    sa.Column('data_source_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['meta_item_types.id'], ),
    sa.ForeignKeyConstraint(['item_type_id'], ['meta_item_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_revision_schemes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scheme_type', sa.String(length=20), nullable=False),
    sa.Column('initial_revision', sa.String(length=10), nullable=True),
    sa.Column('max_number_before_rollover', sa.Integer(), nullable=True),
    sa.Column('item_type_id', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_type_id'], ['meta_item_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_revision_schemes_is_default'), 'meta_revision_schemes', ['is_default'], unique=False)
    op.create_index(op.f('ix_meta_revision_schemes_item_type_id'), 'meta_revision_schemes', ['item_type_id'], unique=False)
    op.create_index('ix_revision_scheme_itemtype', 'meta_revision_schemes', ['item_type_id', 'is_default'], unique=False)
    op.create_table('meta_state_identity_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_id', sa.String(), nullable=False),
    sa.Column('identity_type', sa.String(length=20), nullable=False, comment='dynamic|role'),
    sa.Column('identity_value', sa.String(length=50), nullable=False, comment='动态身份名或角色ID'),
    sa.Column('can_read', sa.Boolean(), nullable=False),
    sa.Column('can_update', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.Column('can_promote', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['meta_lifecycle_states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_view_mappings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('item_type_id', sa.String(), nullable=True),
    sa.Column('form_id', sa.String(), nullable=True),
    sa.Column('grid_view_id', sa.String(), nullable=True),
    sa.Column('identity_id', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['meta_forms.id'], ),
    sa.ForeignKeyConstraint(['grid_view_id'], ['meta_grid_views.id'], ),
    sa.ForeignKeyConstraint(['item_type_id'], ['meta_item_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_workflow_transitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_map_id', sa.String(), nullable=True),
    sa.Column('from_activity_id', sa.String(), nullable=True),
    sa.Column('to_activity_id', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_activity_id'], ['meta_workflow_activities.id'], ),
    sa.ForeignKeyConstraint(['to_activity_id'], ['meta_workflow_activities.id'], ),
    sa.ForeignKeyConstraint(['workflow_map_id'], ['meta_workflow_maps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rbac_role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['rbac_users.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['rbac_permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('rbac_user_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('is_denied', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['rbac_permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['rbac_users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    op.create_table('meta_geometric_indices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('vector', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('algorithm_version', sa.String(), nullable=True),
    sa.Column('signature_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['meta_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_geometric_indices_item_id'), 'meta_geometric_indices', ['item_id'], unique=False)
    op.create_table('meta_item_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_role', sa.String(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['meta_files.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['meta_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_item_files_file_id'), 'meta_item_files', ['file_id'], unique=False)
    op.create_index(op.f('ix_meta_item_files_item_id'), 'meta_item_files', ['item_id'], unique=False)
    op.create_table('meta_item_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=True),
    sa.Column('revision', sa.String(length=10), nullable=True),
    sa.Column('version_label', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('is_released', sa.Boolean(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('released_by_id', sa.Integer(), nullable=True),
    sa.Column('checked_out_by_id', sa.Integer(), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(), nullable=True),
    sa.Column('predecessor_id', sa.String(), nullable=True),
    sa.Column('branch_name', sa.String(length=100), nullable=True),
    sa.Column('branched_from_id', sa.String(), nullable=True),
    sa.Column('properties', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('primary_file_id', sa.String(), nullable=True),
    sa.Column('thumbnail_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['branched_from_id'], ['meta_item_versions.id'], ),
    sa.ForeignKeyConstraint(['checked_out_by_id'], ['rbac_users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['rbac_users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['meta_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['predecessor_id'], ['meta_item_versions.id'], ),
    sa.ForeignKeyConstraint(['released_by_id'], ['rbac_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_item_versions_is_current'), 'meta_item_versions', ['is_current'], unique=False)
    op.create_index(op.f('ix_meta_item_versions_is_released'), 'meta_item_versions', ['is_released'], unique=False)
    op.create_index(op.f('ix_meta_item_versions_item_id'), 'meta_item_versions', ['item_id'], unique=False)
    op.create_table('meta_relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('relationship_type_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('related_id', sa.String(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['rbac_users.id'], ),
    sa.ForeignKeyConstraint(['related_id'], ['meta_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_type_id'], ['meta_relationship_types.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['meta_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_relationships_related_id'), 'meta_relationships', ['related_id'], unique=False)
    op.create_index(op.f('ix_meta_relationships_source_id'), 'meta_relationships', ['source_id'], unique=False)
    op.create_table('meta_workflow_processes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_map_id', sa.String(), nullable=True),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['meta_items.id'], ),
    sa.ForeignKeyConstraint(['workflow_map_id'], ['meta_workflow_maps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_ecos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('eco_type', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('source_version_id', sa.String(), nullable=True),
    sa.Column('target_version_id', sa.String(), nullable=True),
    sa.Column('stage_id', sa.String(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('current_state', sa.String(), nullable=True),
    sa.Column('kanban_state', sa.String(length=20), nullable=True),
    sa.Column('approval_deadline', sa.DateTime(), nullable=True),
    sa.Column('product_version_before', sa.String(length=20), nullable=True),
    sa.Column('product_version_after', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('effectivity_date', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['rbac_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_state'], ['meta_lifecycle_states.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['meta_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_version_id'], ['meta_item_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stage_id'], ['meta_eco_stages.id'], ),
    sa.ForeignKeyConstraint(['target_version_id'], ['meta_item_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_ecos_product_id'), 'meta_ecos', ['product_id'], unique=False)
    op.create_index(op.f('ix_meta_ecos_stage_id'), 'meta_ecos', ['stage_id'], unique=False)
    op.create_index(op.f('ix_meta_ecos_state'), 'meta_ecos', ['state'], unique=False)
    op.create_table('meta_effectivities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('item_id', sa.String(), nullable=True, comment='Deprecated, use version_id'),
    sa.Column('version_id', sa.String(), nullable=True),
    sa.Column('effectivity_type', sa.String(length=32), nullable=False, comment='Type: Date, Lot, Serial, Unit'),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True, comment='Extension data for Lot/Serial/Unit effectivity'),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['meta_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['meta_item_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_effectivities_effectivity_type'), 'meta_effectivities', ['effectivity_type'], unique=False)
    op.create_index(op.f('ix_meta_effectivities_item_id'), 'meta_effectivities', ['item_id'], unique=False)
    op.create_index(op.f('ix_meta_effectivities_version_id'), 'meta_effectivities', ['version_id'], unique=False)
    op.create_table('meta_item_iterations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version_id', sa.String(), nullable=False),
    sa.Column('iteration_number', sa.Integer(), nullable=False),
    sa.Column('iteration_label', sa.String(length=50), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=True),
    sa.Column('properties', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('primary_file_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['rbac_users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['meta_item_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'iteration_number', name='uq_version_iteration')
    )
    op.create_index('ix_iteration_version_latest', 'meta_item_iterations', ['version_id', 'is_latest'], unique=False)
    op.create_index(op.f('ix_meta_item_iterations_is_latest'), 'meta_item_iterations', ['is_latest'], unique=False)
    op.create_index(op.f('ix_meta_item_iterations_version_id'), 'meta_item_iterations', ['version_id'], unique=False)
    op.create_table('meta_version_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_role', sa.String(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('snapshot_path', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['meta_item_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_version_files_file_id'), 'meta_version_files', ['file_id'], unique=False)
    op.create_index(op.f('ix_meta_version_files_file_role'), 'meta_version_files', ['file_role'], unique=False)
    op.create_index(op.f('ix_meta_version_files_version_id'), 'meta_version_files', ['version_id'], unique=False)
    op.create_index('uq_version_file_role', 'meta_version_files', ['version_id', 'file_id', 'file_role'], unique=True)
    op.create_table('meta_version_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('changes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['rbac_users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['meta_item_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_version_history_version_id'), 'meta_version_history', ['version_id'], unique=False)
    op.create_table('meta_workflow_activity_instances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('process_id', sa.String(), nullable=True),
    sa.Column('activity_id', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['meta_workflow_activities.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['meta_workflow_processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_eco_approvals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('eco_id', sa.String(), nullable=False),
    sa.Column('stage_id', sa.String(), nullable=False),
    sa.Column('approval_type', sa.String(length=20), nullable=True),
    sa.Column('required_role', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eco_id'], ['meta_ecos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['meta_eco_stages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['rbac_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_eco_approvals_eco_id'), 'meta_eco_approvals', ['eco_id'], unique=False)
    op.create_index(op.f('ix_meta_eco_approvals_status'), 'meta_eco_approvals', ['status'], unique=False)
    op.create_table('meta_eco_bom_changes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('eco_id', sa.String(), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('relationship_item_id', sa.String(), nullable=True),
    sa.Column('parent_item_id', sa.String(), nullable=True),
    sa.Column('child_item_id', sa.String(), nullable=True),
    sa.Column('old_qty', sa.Float(), nullable=True),
    sa.Column('old_uom', sa.String(length=50), nullable=True),
    sa.Column('old_sequence', sa.Integer(), nullable=True),
    sa.Column('old_properties', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('new_qty', sa.Float(), nullable=True),
    sa.Column('new_uom', sa.String(length=50), nullable=True),
    sa.Column('new_sequence', sa.Integer(), nullable=True),
    sa.Column('new_properties', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('conflict', sa.Boolean(), nullable=True),
    sa.Column('conflict_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_item_id'], ['meta_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['eco_id'], ['meta_ecos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_item_id'], ['meta_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['relationship_item_id'], ['meta_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_eco_bom_change_child', 'meta_eco_bom_changes', ['child_item_id'], unique=False)
    op.create_index('ix_eco_bom_change_parent', 'meta_eco_bom_changes', ['parent_item_id'], unique=False)
    op.create_index(op.f('ix_meta_eco_bom_changes_change_type'), 'meta_eco_bom_changes', ['change_type'], unique=False)
    op.create_index(op.f('ix_meta_eco_bom_changes_eco_id'), 'meta_eco_bom_changes', ['eco_id'], unique=False)
    op.create_table('meta_workflow_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('activity_instance_id', sa.String(), nullable=True),
    sa.Column('assignee_type', sa.String(), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_role_id', sa.Integer(), nullable=True),
    sa.Column('dynamic_identity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_instance_id'], ['meta_workflow_activity_instances.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_role_id'], ['rbac_roles.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['rbac_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meta_workflow_tasks')
    op.drop_index(op.f('ix_meta_eco_bom_changes_eco_id'), table_name='meta_eco_bom_changes')
    op.drop_index(op.f('ix_meta_eco_bom_changes_change_type'), table_name='meta_eco_bom_changes')
    op.drop_index('ix_eco_bom_change_parent', table_name='meta_eco_bom_changes')
    op.drop_index('ix_eco_bom_change_child', table_name='meta_eco_bom_changes')
    op.drop_table('meta_eco_bom_changes')
    op.drop_index(op.f('ix_meta_eco_approvals_status'), table_name='meta_eco_approvals')
    op.drop_index(op.f('ix_meta_eco_approvals_eco_id'), table_name='meta_eco_approvals')
    op.drop_table('meta_eco_approvals')
    op.drop_table('meta_workflow_activity_instances')
    op.drop_index(op.f('ix_meta_version_history_version_id'), table_name='meta_version_history')
    op.drop_table('meta_version_history')
    op.drop_index('uq_version_file_role', table_name='meta_version_files')
    op.drop_index(op.f('ix_meta_version_files_version_id'), table_name='meta_version_files')
    op.drop_index(op.f('ix_meta_version_files_file_role'), table_name='meta_version_files')
    op.drop_index(op.f('ix_meta_version_files_file_id'), table_name='meta_version_files')
    op.drop_table('meta_version_files')
    op.drop_index(op.f('ix_meta_item_iterations_version_id'), table_name='meta_item_iterations')
    op.drop_index(op.f('ix_meta_item_iterations_is_latest'), table_name='meta_item_iterations')
    op.drop_index('ix_iteration_version_latest', table_name='meta_item_iterations')
    op.drop_table('meta_item_iterations')
    op.drop_index(op.f('ix_meta_effectivities_version_id'), table_name='meta_effectivities')
    op.drop_index(op.f('ix_meta_effectivities_item_id'), table_name='meta_effectivities')
    op.drop_index(op.f('ix_meta_effectivities_effectivity_type'), table_name='meta_effectivities')
    op.drop_table('meta_effectivities')
    op.drop_index(op.f('ix_meta_ecos_state'), table_name='meta_ecos')
    op.drop_index(op.f('ix_meta_ecos_stage_id'), table_name='meta_ecos')
    op.drop_index(op.f('ix_meta_ecos_product_id'), table_name='meta_ecos')
    op.drop_table('meta_ecos')
    op.drop_table('meta_workflow_processes')
    op.drop_index(op.f('ix_meta_relationships_source_id'), table_name='meta_relationships')
    op.drop_index(op.f('ix_meta_relationships_related_id'), table_name='meta_relationships')
    op.drop_table('meta_relationships')
    op.drop_index(op.f('ix_meta_item_versions_item_id'), table_name='meta_item_versions')
    op.drop_index(op.f('ix_meta_item_versions_is_released'), table_name='meta_item_versions')
    op.drop_index(op.f('ix_meta_item_versions_is_current'), table_name='meta_item_versions')
    op.drop_table('meta_item_versions')
    op.drop_index(op.f('ix_meta_item_files_item_id'), table_name='meta_item_files')
    op.drop_index(op.f('ix_meta_item_files_file_id'), table_name='meta_item_files')
    op.drop_table('meta_item_files')
    op.drop_index(op.f('ix_meta_geometric_indices_item_id'), table_name='meta_geometric_indices')
    op.drop_table('meta_geometric_indices')
    op.drop_table('rbac_user_permissions')
    op.drop_table('rbac_role_permissions')
    op.drop_table('meta_workflow_transitions')
    op.drop_table('meta_view_mappings')
    op.drop_table('meta_state_identity_permissions')
    op.drop_index('ix_revision_scheme_itemtype', table_name='meta_revision_schemes')
    op.drop_index(op.f('ix_meta_revision_schemes_item_type_id'), table_name='meta_revision_schemes')
    op.drop_index(op.f('ix_meta_revision_schemes_is_default'), table_name='meta_revision_schemes')
    op.drop_table('meta_revision_schemes')
    op.drop_table('meta_properties')
    op.drop_table('meta_lifecycle_transitions')
    op.drop_index(op.f('ix_meta_items_source_id'), table_name='meta_items')
    op.drop_index(op.f('ix_meta_items_related_id'), table_name='meta_items')
    op.drop_index(op.f('ix_meta_items_item_type_id'), table_name='meta_items')
    op.drop_index(op.f('ix_meta_items_config_id'), table_name='meta_items')
    op.drop_table('meta_items')
    op.drop_table('meta_extensions')
    op.drop_index(op.f('ix_cad_conversion_jobs_status'), table_name='cad_conversion_jobs')
    op.drop_table('cad_conversion_jobs')
    op.drop_index(op.f('ix_auth_org_memberships_user_id'), table_name='auth_org_memberships')
    op.drop_index(op.f('ix_auth_org_memberships_tenant_id'), table_name='auth_org_memberships')
    op.drop_index(op.f('ix_auth_org_memberships_org_id'), table_name='auth_org_memberships')
    op.drop_table('auth_org_memberships')
    op.drop_table('auth_credentials')
    op.drop_table('rbac_user_roles')
    op.drop_table('rbac_permissions')
    op.drop_table('meta_workflow_activities')
    op.drop_table('meta_relationship_types')
    op.drop_table('meta_lifecycle_states')
    op.drop_table('meta_item_types')
    op.drop_table('meta_grid_columns')
    op.drop_table('meta_form_fields')
    op.drop_index(op.f('ix_meta_files_file_type'), table_name='meta_files')
    op.drop_index(op.f('ix_meta_files_checksum'), table_name='meta_files')
    op.drop_table('meta_files')
    op.drop_table('meta_app_registry')
    op.drop_table('meta_access')
    op.drop_index(op.f('ix_auth_users_tenant_id'), table_name='auth_users')
    op.drop_table('auth_users')
    op.drop_index(op.f('ix_auth_organizations_tenant_id'), table_name='auth_organizations')
    op.drop_table('auth_organizations')
    op.drop_table('users')
    op.drop_table('rbac_users')
    op.drop_table('rbac_roles')
    op.drop_table('rbac_resources')
    op.drop_table('meta_workflow_maps')
    op.drop_table('meta_vaults')
    op.drop_table('meta_permissions')
    op.drop_table('meta_methods')
    op.drop_table('meta_lifecycle_maps')
    op.drop_table('meta_grid_views')
    op.drop_table('meta_forms')
    op.drop_table('meta_extension_points')
    op.drop_table('meta_eco_stages')
    op.drop_index(op.f('ix_meta_conversion_jobs_status'), table_name='meta_conversion_jobs')
    op.drop_table('meta_conversion_jobs')
    op.drop_table('auth_tenants')
    # ### end Alembic commands ###
