"""Shared test fixtures for governance router discoverability payloads."""
from __future__ import annotations

from typing import Dict

from yuantus.meta_engine.web.subcontracting_governance_discoverability import (
    GOVERNANCE_ACTION_SUPPORT_SPECS,
    GOVERNANCE_FOLLOW_THROUGH_BURNDOWN_ALIAS_SPECS,
    GOVERNANCE_FOLLOW_THROUGH_DIGEST_ALIAS_SPECS,
    GOVERNANCE_FOLLOW_THROUGH_HISTORY_ALIAS_SPECS,
    GOVERNANCE_REVIEW_DISCOVERABILITY_SPECS,
    GOVERNANCE_ROOT_DISCOVERABILITY_SPECS,
    build_governance_discoverability,
)
from yuantus.meta_engine.web.subcontracting_governance_row_discoverability import (
    build_governance_action_actor_row_urls,
    build_governance_action_batch_row_urls,
    build_governance_action_queue_summary_row_urls,
    build_governance_action_row_urls,
    build_governance_correlation_preset_row_urls,
    build_governance_preset_row_urls,
    build_governance_queue_row_urls,
    build_governance_responsibility_actor_summary_row_urls,
    build_governance_responsibility_team_summary_row_urls,
    build_governance_review_handoff_acceptance_actor_row_urls,
    build_governance_review_handoff_acceptance_queue_row_urls,
    build_governance_review_handoff_acceptance_follow_through_owner_row_urls,
    build_governance_review_handoff_acceptance_follow_through_batch_row_urls,
    build_governance_review_handoff_acceptance_follow_through_view_row_urls,
    build_governance_review_handoff_acceptance_follow_through_trend_row_urls,
    build_governance_review_handoff_acceptance_follow_through_status_row_urls,
    build_governance_review_handoff_acceptance_entry_efficiency_row_urls,
    build_governance_review_handoff_acceptance_action_row_urls,
    build_governance_review_handoff_acceptance_status_row_urls,
    build_governance_review_handoff_acceptance_selection_mode_row_urls,
    build_governance_review_handoff_acceptance_entry_efficiency_snapshot_urls,
    build_governance_review_handoff_acceptance_digest_history_snapshot_urls,
    build_governance_review_handoff_follow_through_digest_history_snapshot_urls,
    build_governance_review_handoff_follow_through_burndown_snapshot_urls,
    build_governance_review_handoff_follow_through_digest_snapshot_urls,
    build_governance_review_handoff_acceptance_trends_snapshot_urls,
    build_governance_review_handoff_acceptance_trend_row_urls,
    build_governance_review_digest_burndown_snapshot_urls,
    build_governance_review_digest_history_snapshot_urls,
    build_governance_review_handoff_ledger_snapshot_urls,
    build_governance_review_handoff_history_row_urls,
    build_governance_review_handoff_row_urls,
)


def build_governance_overview_discoverability_bundle() -> Dict[str, str]:
    return build_governance_discoverability(
        "governance_inbox",
        include_export=True,
        link_specs=GOVERNANCE_ROOT_DISCOVERABILITY_SPECS,
    )


def build_governance_review_discoverability_bundle(
    self_code: str,
    *,
    include_export: bool = True,
) -> Dict[str, str]:
    return build_governance_discoverability(
        self_code,
        include_export=include_export,
        link_specs=GOVERNANCE_REVIEW_DISCOVERABILITY_SPECS,
    )


def build_governance_follow_through_digest_discoverability_bundle() -> Dict[str, str]:
    return build_governance_discoverability(
        "governance_review_handoff_acceptance_follow_through_digest",
        include_export=True,
        link_specs=(
            *GOVERNANCE_REVIEW_DISCOVERABILITY_SPECS,
            *GOVERNANCE_FOLLOW_THROUGH_DIGEST_ALIAS_SPECS,
        ),
    )


def build_governance_follow_through_burndown_discoverability_bundle() -> Dict[str, str]:
    return build_governance_discoverability(
        "governance_review_handoff_acceptance_follow_through_burndown",
        include_export=True,
        link_specs=(
            *GOVERNANCE_REVIEW_DISCOVERABILITY_SPECS,
            *GOVERNANCE_FOLLOW_THROUGH_BURNDOWN_ALIAS_SPECS,
        ),
    )


def build_governance_follow_through_history_discoverability_bundle() -> Dict[str, str]:
    return build_governance_discoverability(
        "governance_review_handoff_acceptance_follow_through_history",
        include_export=True,
        link_specs=(
            *GOVERNANCE_REVIEW_DISCOVERABILITY_SPECS,
            *GOVERNANCE_FOLLOW_THROUGH_HISTORY_ALIAS_SPECS,
        ),
    )


def build_governance_action_discoverability_bundle(
    self_code: str = "governance_action",
    *,
    include_export: bool = False,
) -> Dict[str, str]:
    return build_governance_discoverability(
        self_code,
        include_export=include_export,
        link_specs=(
            *GOVERNANCE_REVIEW_DISCOVERABILITY_SPECS,
            *GOVERNANCE_ACTION_SUPPORT_SPECS,
        ),
    )


def build_governance_queue_row_urls_bundle(
    *,
    queue_type: str = "approval_debt",
    consumer_urls: Dict[str, str],
    order_id: str = "so-1",
    disposition_event_id: str | None = "evt-1",
) -> Dict[str, str]:
    return build_governance_queue_row_urls(
        queue_type=queue_type,
        consumer_urls=consumer_urls,
        order_id=order_id,
        disposition_event_id=disposition_event_id,
    )


def build_governance_preset_row_urls_bundle(
    *,
    effective_filters: Dict[str, object],
    preset_code: str = "my_governance_queue",
    preview_limit: int = 25,
    vendor_id: str = "vendor-1",
    responsible_actor: str | None = "qa-reviewer",
    responsible_team: str | None = "governance",
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
) -> Dict[str, str]:
    return build_governance_preset_row_urls(
        effective_filters=effective_filters,
        preset_query={
            "preset_code": preset_code,
            "preview_limit": preview_limit,
            "vendor_id": vendor_id,
            "responsible_actor": responsible_actor,
            "responsible_team": responsible_team,
            "on_call_owner": on_call_owner,
            "on_call_team": on_call_team,
        },
        preview_limit=preview_limit,
    )


def build_governance_correlation_preset_row_urls_bundle(
    *,
    effective_filters: Dict[str, object],
    correlation_filters: Dict[str, object] | None = None,
    preset_code: str = "critical_triage",
    preview_limit: int = 25,
    trend_days: int = 10,
    forecast_window_days: int = 5,
    vendor_id: str = "vendor-1",
    responsible_actor: str | None = "qa-reviewer",
    responsible_team: str | None = "governance",
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
) -> Dict[str, str]:
    return build_governance_correlation_preset_row_urls(
        effective_filters=effective_filters,
        correlation_filters=correlation_filters or effective_filters,
        preset_query={
            "preset_code": preset_code,
            "preview_limit": preview_limit,
            "trend_days": trend_days,
            "forecast_window_days": forecast_window_days,
            "vendor_id": vendor_id,
            "responsible_actor": responsible_actor,
            "responsible_team": responsible_team,
            "on_call_owner": on_call_owner,
            "on_call_team": on_call_team,
        },
        preview_limit=preview_limit,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
    )


def build_governance_review_handoff_row_urls_bundle(
    *,
    vendor_id: str = "vendor-1",
    responsible_actor: str | None = "qa-reviewer",
    responsible_team: str | None = "governance",
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    preset_code: str = "critical_triage",
    preview_limit: int = 25,
    review_limit: int = 10,
    trend_days: int = 10,
    forecast_window_days: int = 5,
    handoff_limit: int = 5,
    queue_type: str = "cleanup_debt",
    source_ref: str = "map-1",
) -> Dict[str, str]:
    return build_governance_review_handoff_row_urls(
        digest_query={
            "vendor_id": vendor_id,
            "responsible_actor": responsible_actor,
            "responsible_team": responsible_team,
            "on_call_owner": on_call_owner,
            "on_call_team": on_call_team,
            "preset_code": preset_code,
            "preview_limit": preview_limit,
            "review_limit": review_limit,
            "trend_days": trend_days,
            "forecast_window_days": forecast_window_days,
        },
        history_query={
            "vendor_id": vendor_id,
            "queue_type": queue_type,
            "source_ref": source_ref,
            "on_call_owner": on_call_owner,
            "on_call_team": on_call_team,
        },
        correlation_query={
            "vendor_id": vendor_id,
            "queue_type": queue_type,
            "trend_days": trend_days,
            "forecast_window_days": forecast_window_days,
        },
        handoff_limit=handoff_limit,
    )


def build_governance_review_digest_row_urls_bundle(
    *,
    vendor_id: str = "vendor-1",
    responsible_actor: str | None = "qa-reviewer",
    responsible_team: str | None = "governance",
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    preset_code: str = "critical_triage",
    preview_limit: int = 25,
    review_limit: int = 5,
    trend_days: int = 10,
    forecast_window_days: int = 5,
    handoff_limit: int = 20,
    queue_type: str = "cleanup_debt",
    source_ref: str = "map-1",
) -> Dict[str, str]:
    return build_governance_review_handoff_row_urls(
        digest_query={
            "vendor_id": vendor_id,
            "responsible_actor": responsible_actor,
            "responsible_team": responsible_team,
            "on_call_owner": on_call_owner,
            "on_call_team": on_call_team,
            "preset_code": preset_code,
            "preview_limit": preview_limit,
            "review_limit": review_limit,
            "trend_days": trend_days,
            "forecast_window_days": forecast_window_days,
        },
        history_query={
            "vendor_id": vendor_id,
            "queue_type": queue_type,
            "source_ref": source_ref,
            "on_call_owner": on_call_owner,
            "on_call_team": on_call_team,
        },
        correlation_query={
            "vendor_id": vendor_id,
            "responsible_actor": responsible_actor,
            "responsible_team": responsible_team,
            "queue_type": queue_type,
            "include_completed": False,
            "include_controlled": False,
            "actionable_only": True,
            "on_call_owner": on_call_owner,
            "include_watch_alerts": True,
            "trend_days": trend_days,
            "forecast_window_days": forecast_window_days,
        },
        handoff_limit=handoff_limit,
    )


def build_governance_review_handoff_history_row_urls_bundle(
    *,
    vendor_id: str = "vendor-1",
    responsible_actor: str | None = "qa-reviewer",
    responsible_team: str | None = "governance",
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    current_handoff_owner: str | None = None,
    current_handoff_team: str | None = None,
    accepted_by: str | None = None,
    action_batch_id: str | None = None,
    acceptance_status: str | None = None,
    preset_code: str = "critical_triage",
    preview_limit: int = 25,
    review_limit: int = 10,
    handoff_limit: int = 5,
    history_limit: int = 6,
    trend_days: int = 10,
    forecast_window_days: int = 5,
    sort_by: str = "recent",
    selection_view_id: str | None = None,
    selection_mode: str | None = None,
    follow_through_status: str | None = None,
    action_origin: str | None = None,
    open_only: bool | None = None,
    activity_date: str | None = None,
    activity_kind: str | None = None,
    include_scoped_correlation: bool = False,
    queue_type: str = "cleanup_debt",
    source_ref: str = "map-1",
) -> Dict[str, str]:
    has_follow_through_scope = any(
        value is not None
        for value in (
            selection_view_id,
            selection_mode,
            follow_through_status,
            activity_date,
            activity_kind,
        )
    ) or open_only is not None
    return build_governance_review_handoff_history_row_urls(
        handoff_query={
            "vendor_id": vendor_id,
            "responsible_actor": responsible_actor,
            "responsible_team": responsible_team,
            "on_call_owner": on_call_owner,
            "on_call_team": on_call_team,
            "preset_code": preset_code,
            "preview_limit": preview_limit,
            "review_limit": review_limit,
            "handoff_limit": handoff_limit,
            "trend_days": trend_days,
            "forecast_window_days": forecast_window_days,
        },
        acceptance_scope_query={
            "vendor_id": vendor_id,
            "responsible_actor": responsible_actor,
            "responsible_team": responsible_team,
            "on_call_owner": on_call_owner,
            "on_call_team": on_call_team,
            "current_handoff_owner": current_handoff_owner,
            "current_handoff_team": current_handoff_team,
            "preset_code": preset_code,
            "accepted_by": accepted_by,
            "action_batch_id": action_batch_id,
            "acceptance_status": acceptance_status,
            "action_origin": action_origin,
            "queue_type": queue_type,
            "preview_limit": preview_limit,
            "review_limit": review_limit,
            **(
                {
                    "trend_days": trend_days,
                    "forecast_window_days": forecast_window_days,
                    "selection_view_id": selection_view_id,
                    "selection_mode": selection_mode,
                    "follow_through_status": follow_through_status,
                    "open_only": open_only,
                    "history_limit": history_limit,
                    "handoff_limit": handoff_limit,
                    "sort_by": sort_by,
                    "activity_date": activity_date,
                    "activity_kind": activity_kind,
                }
                if has_follow_through_scope
                else {
                    "handoff_limit": handoff_limit,
                    "history_limit": history_limit,
                    "trend_days": trend_days,
                    "forecast_window_days": forecast_window_days,
                    "sort_by": sort_by,
                }
            ),
        },
        digest_query={
            "vendor_id": vendor_id,
            "responsible_actor": responsible_actor,
            "responsible_team": responsible_team,
            "on_call_owner": on_call_owner,
            "on_call_team": on_call_team,
            "current_handoff_owner": current_handoff_owner,
            "current_handoff_team": current_handoff_team,
            "preset_code": preset_code,
            "accepted_by": accepted_by,
            "action_batch_id": action_batch_id,
            "acceptance_status": acceptance_status,
            "queue_type": queue_type,
            "preview_limit": preview_limit,
            "review_limit": review_limit,
            "trend_days": trend_days,
            "forecast_window_days": forecast_window_days,
        },
        history_query={
            "vendor_id": vendor_id,
            "queue_type": queue_type,
            "source_ref": source_ref,
            "on_call_owner": on_call_owner,
            "on_call_team": on_call_team,
        },
        correlation_query={
            "vendor_id": vendor_id,
            **(
                {
                    "responsible_actor": responsible_actor,
                    "responsible_team": responsible_team,
                }
                if include_scoped_correlation
                else {}
            ),
            "queue_type": queue_type,
            **(
                {
                    "on_call_owner": on_call_owner,
                    "on_call_team": on_call_team,
                }
                if include_scoped_correlation
                else {}
            ),
            "trend_days": trend_days,
            "forecast_window_days": forecast_window_days,
        },
        history_limit=history_limit,
        sort_by=sort_by,
    )


def build_governance_review_digest_history_snapshot_urls_bundle(
    *,
    vendor_id: str | None = "vendor-1",
    queue_type: str | None = "cleanup_debt",
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    include_watch_alerts: bool = True,
    limit: int = 200,
    trend_days: int = 10,
    forecast_window_days: int = 5,
) -> Dict[str, str]:
    return build_governance_review_digest_history_snapshot_urls(
        vendor_id=vendor_id,
        queue_type=queue_type,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        include_watch_alerts=include_watch_alerts,
        limit=limit,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
    )


def build_governance_review_digest_burndown_snapshot_urls_bundle(
    *,
    vendor_id: str | None = "vendor-1",
    queue_type: str | None = "cleanup_debt",
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    include_watch_alerts: bool = True,
    limit: int = 200,
    trend_days: int = 10,
    forecast_window_days: int = 5,
) -> Dict[str, str]:
    return build_governance_review_digest_burndown_snapshot_urls(
        vendor_id=vendor_id,
        queue_type=queue_type,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        include_watch_alerts=include_watch_alerts,
        limit=limit,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
    )


def build_governance_review_handoff_ledger_snapshot_urls_bundle(
    *,
    vendor_id: str | None = "vendor-1",
    responsible_actor: str | None = "qa-reviewer",
    responsible_team: str | None = "governance",
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    current_handoff_owner: str | None = None,
    current_handoff_team: str | None = None,
    preset_code: str | None = "critical_triage",
    accepted_by: str | None = "ops-oncall",
    action_batch_id: str | None = None,
    acceptance_action: str | None = None,
    acceptance_status: str | None = None,
    selection_view_id: str | None = None,
    selection_mode: str | None = None,
    follow_through_status: str | None = None,
    action_origin: str | None = None,
    queue_type: str | None = None,
    open_only: bool = False,
    activity_date: str | None = None,
    activity_kind: str | None = None,
    preview_limit: int = 25,
    review_limit: int = 10,
    handoff_limit: int = 5,
    history_limit: int = 8,
    trend_days: int = 10,
    forecast_window_days: int = 5,
    sort_by: str = "priority",
) -> Dict[str, str]:
    return build_governance_review_handoff_ledger_snapshot_urls(
        vendor_id=vendor_id,
        responsible_actor=responsible_actor,
        responsible_team=responsible_team,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        current_handoff_owner=current_handoff_owner,
        current_handoff_team=current_handoff_team,
        preset_code=preset_code,
        accepted_by=accepted_by,
        action_batch_id=action_batch_id,
        acceptance_action=acceptance_action,
        acceptance_status=acceptance_status,
        selection_view_id=selection_view_id,
        selection_mode=selection_mode,
        follow_through_status=follow_through_status,
        action_origin=action_origin,
        queue_type=queue_type,
        open_only=open_only,
        activity_date=activity_date,
        activity_kind=activity_kind,
        preview_limit=preview_limit,
        review_limit=review_limit,
        handoff_limit=handoff_limit,
        history_limit=history_limit,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
        sort_by=sort_by,
    )


def build_governance_review_handoff_acceptance_digest_history_snapshot_urls_bundle(
    *,
    vendor_id: str | None = "vendor-1",
    responsible_actor: str | None = "qa-reviewer",
    responsible_team: str | None = "governance",
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    current_handoff_owner: str | None = None,
    current_handoff_team: str | None = None,
    preset_code: str | None = "critical_triage",
    accepted_by: str | None = "ops-oncall",
    action_batch_id: str | None = None,
    acceptance_action: str | None = None,
    acceptance_status: str | None = None,
    selection_view_id: str | None = None,
    selection_mode: str | None = None,
    follow_through_status: str | None = None,
    action_origin: str | None = None,
    queue_type: str | None = None,
    open_only: bool = False,
    activity_date: str | None = None,
    activity_kind: str | None = None,
    preview_limit: int = 25,
    review_limit: int = 10,
    handoff_limit: int = 5,
    history_limit: int = 8,
    trend_days: int = 10,
    forecast_window_days: int = 5,
    sort_by: str = "priority",
) -> Dict[str, str]:
    return build_governance_review_handoff_acceptance_digest_history_snapshot_urls(
        vendor_id=vendor_id,
        responsible_actor=responsible_actor,
        responsible_team=responsible_team,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        current_handoff_owner=current_handoff_owner,
        current_handoff_team=current_handoff_team,
        preset_code=preset_code,
        accepted_by=accepted_by,
        action_batch_id=action_batch_id,
        acceptance_action=acceptance_action,
        acceptance_status=acceptance_status,
        selection_view_id=selection_view_id,
        selection_mode=selection_mode,
        follow_through_status=follow_through_status,
        action_origin=action_origin,
        queue_type=queue_type,
        open_only=open_only,
        activity_date=activity_date,
        activity_kind=activity_kind,
        preview_limit=preview_limit,
        review_limit=review_limit,
        handoff_limit=handoff_limit,
        history_limit=history_limit,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
        sort_by=sort_by,
    )


def build_governance_review_handoff_follow_through_digest_history_snapshot_urls_bundle(
    *,
    vendor_id: str | None = "vendor-1",
    responsible_actor: str | None = "qa-reviewer",
    responsible_team: str | None = "governance",
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    current_handoff_owner: str | None = None,
    current_handoff_team: str | None = None,
    preset_code: str | None = "critical_triage",
    accepted_by: str | None = "ops-oncall",
    action_batch_id: str | None = None,
    acceptance_action: str | None = None,
    acceptance_status: str | None = None,
    selection_view_id: str | None = None,
    selection_mode: str | None = None,
    follow_through_status: str | None = None,
    action_origin: str | None = None,
    queue_type: str | None = None,
    open_only: bool = False,
    activity_date: str | None = None,
    activity_kind: str | None = None,
    preview_limit: int = 25,
    review_limit: int = 10,
    handoff_limit: int = 5,
    history_limit: int = 8,
    trend_days: int = 10,
    forecast_window_days: int = 5,
    sort_by: str = "priority",
) -> Dict[str, str]:
    return build_governance_review_handoff_follow_through_digest_history_snapshot_urls(
        vendor_id=vendor_id,
        responsible_actor=responsible_actor,
        responsible_team=responsible_team,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        current_handoff_owner=current_handoff_owner,
        current_handoff_team=current_handoff_team,
        preset_code=preset_code,
        accepted_by=accepted_by,
        action_batch_id=action_batch_id,
        acceptance_action=acceptance_action,
        acceptance_status=acceptance_status,
        selection_view_id=selection_view_id,
        selection_mode=selection_mode,
        follow_through_status=follow_through_status,
        action_origin=action_origin,
        queue_type=queue_type,
        open_only=open_only,
        activity_date=activity_date,
        activity_kind=activity_kind,
        preview_limit=preview_limit,
        review_limit=review_limit,
        handoff_limit=handoff_limit,
        history_limit=history_limit,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
        sort_by=sort_by,
    )


def build_governance_review_handoff_follow_through_digest_snapshot_urls_bundle(
    *,
    vendor_id: str | None = "vendor-1",
    responsible_actor: str | None = "qa-reviewer",
    responsible_team: str | None = "governance",
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    current_handoff_owner: str | None = None,
    current_handoff_team: str | None = None,
    preset_code: str | None = "critical_triage",
    accepted_by: str | None = "ops-oncall",
    action_batch_id: str | None = None,
    acceptance_action: str | None = None,
    acceptance_status: str | None = None,
    selection_view_id: str | None = None,
    selection_mode: str | None = None,
    follow_through_status: str | None = None,
    action_origin: str | None = None,
    queue_type: str | None = None,
    open_only: bool = False,
    activity_date: str | None = None,
    activity_kind: str | None = None,
    preview_limit: int = 25,
    review_limit: int = 10,
    handoff_limit: int = 5,
    history_limit: int = 8,
    trend_days: int = 10,
    forecast_window_days: int = 5,
    sort_by: str = "priority",
) -> Dict[str, str]:
    return build_governance_review_handoff_follow_through_digest_snapshot_urls(
        vendor_id=vendor_id,
        responsible_actor=responsible_actor,
        responsible_team=responsible_team,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        current_handoff_owner=current_handoff_owner,
        current_handoff_team=current_handoff_team,
        preset_code=preset_code,
        accepted_by=accepted_by,
        action_batch_id=action_batch_id,
        acceptance_action=acceptance_action,
        acceptance_status=acceptance_status,
        selection_view_id=selection_view_id,
        selection_mode=selection_mode,
        follow_through_status=follow_through_status,
        action_origin=action_origin,
        queue_type=queue_type,
        open_only=open_only,
        activity_date=activity_date,
        activity_kind=activity_kind,
        preview_limit=preview_limit,
        review_limit=review_limit,
        handoff_limit=handoff_limit,
        history_limit=history_limit,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
        sort_by=sort_by,
    )


def build_governance_review_handoff_follow_through_burndown_snapshot_urls_bundle(
    *,
    vendor_id: str | None = "vendor-1",
    responsible_actor: str | None = "qa-reviewer",
    responsible_team: str | None = "governance",
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    current_handoff_owner: str | None = None,
    current_handoff_team: str | None = None,
    preset_code: str | None = "critical_triage",
    accepted_by: str | None = "ops-oncall",
    action_batch_id: str | None = None,
    acceptance_status: str | None = None,
    selection_view_id: str | None = None,
    selection_mode: str | None = None,
    follow_through_status: str | None = None,
    action_origin: str | None = None,
    queue_type: str | None = None,
    open_only: bool = False,
    activity_date: str | None = None,
    activity_kind: str | None = None,
    preview_limit: int = 25,
    review_limit: int = 10,
    handoff_limit: int = 5,
    history_limit: int = 8,
    trend_days: int = 10,
    forecast_window_days: int = 5,
    sort_by: str = "priority",
) -> Dict[str, str]:
    return build_governance_review_handoff_follow_through_burndown_snapshot_urls(
        vendor_id=vendor_id,
        responsible_actor=responsible_actor,
        responsible_team=responsible_team,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        current_handoff_owner=current_handoff_owner,
        current_handoff_team=current_handoff_team,
        preset_code=preset_code,
        accepted_by=accepted_by,
        action_batch_id=action_batch_id,
        acceptance_status=acceptance_status,
        selection_view_id=selection_view_id,
        selection_mode=selection_mode,
        follow_through_status=follow_through_status,
        action_origin=action_origin,
        queue_type=queue_type,
        open_only=open_only,
        activity_date=activity_date,
        activity_kind=activity_kind,
        preview_limit=preview_limit,
        review_limit=review_limit,
        handoff_limit=handoff_limit,
        history_limit=history_limit,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
        sort_by=sort_by,
    )


def build_governance_review_handoff_acceptance_trends_snapshot_urls_bundle(
    *,
    vendor_id: str | None = "vendor-1",
    responsible_actor: str | None = "qa-reviewer",
    responsible_team: str | None = "governance",
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    current_handoff_owner: str | None = None,
    current_handoff_team: str | None = None,
    preset_code: str | None = "critical_triage",
    accepted_by: str | None = "ops-oncall",
    action_batch_id: str | None = None,
    acceptance_action: str | None = None,
    acceptance_status: str | None = None,
    selection_view_id: str | None = None,
    selection_mode: str | None = None,
    follow_through_status: str | None = None,
    action_origin: str | None = None,
    queue_type: str | None = None,
    open_only: bool = False,
    activity_date: str | None = None,
    activity_kind: str | None = None,
    preview_limit: int = 25,
    review_limit: int = 10,
    handoff_limit: int = 5,
    history_limit: int = 8,
    trend_days: int = 10,
    forecast_window_days: int = 5,
    sort_by: str = "priority",
) -> Dict[str, str]:
    return build_governance_review_handoff_acceptance_trends_snapshot_urls(
        vendor_id=vendor_id,
        responsible_actor=responsible_actor,
        responsible_team=responsible_team,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        current_handoff_owner=current_handoff_owner,
        current_handoff_team=current_handoff_team,
        preset_code=preset_code,
        accepted_by=accepted_by,
        action_batch_id=action_batch_id,
        acceptance_action=acceptance_action,
        acceptance_status=acceptance_status,
        selection_view_id=selection_view_id,
        selection_mode=selection_mode,
        follow_through_status=follow_through_status,
        action_origin=action_origin,
        queue_type=queue_type,
        open_only=open_only,
        activity_date=activity_date,
        activity_kind=activity_kind,
        preview_limit=preview_limit,
        review_limit=review_limit,
        handoff_limit=handoff_limit,
        history_limit=history_limit,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
        sort_by=sort_by,
    )


def build_governance_review_handoff_acceptance_digest_row_urls_bundle(
    *,
    vendor_id: str = "vendor-1",
    responsible_actor: str | None = "qa-reviewer",
    responsible_team: str | None = "governance",
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    current_handoff_owner: str | None = None,
    current_handoff_team: str | None = None,
    accepted_by: str | None = "ops-oncall",
    action_batch_id: str | None = None,
    acceptance_status: str | None = None,
    preset_code: str = "critical_triage",
    preview_limit: int = 25,
    review_limit: int = 10,
    handoff_limit: int = 5,
    history_limit: int = 8,
    trend_days: int = 10,
    forecast_window_days: int = 5,
    sort_by: str = "priority",
    selection_view_id: str | None = None,
    selection_mode: str | None = None,
    follow_through_status: str | None = None,
    action_origin: str | None = None,
    open_only: bool | None = None,
    queue_type: str = "cleanup_debt",
    source_ref: str = "map-1",
) -> Dict[str, str]:
    return build_governance_review_handoff_history_row_urls(
        handoff_query={
            "vendor_id": vendor_id,
            "responsible_actor": responsible_actor,
            "responsible_team": responsible_team,
            "on_call_owner": on_call_owner,
            "on_call_team": on_call_team,
            "preset_code": preset_code,
            "preview_limit": preview_limit,
            "review_limit": review_limit,
            "handoff_limit": handoff_limit,
            "trend_days": trend_days,
            "forecast_window_days": forecast_window_days,
        },
        acceptance_scope_query={
            "vendor_id": vendor_id,
            "responsible_actor": responsible_actor,
            "responsible_team": responsible_team,
            "on_call_owner": on_call_owner,
            "on_call_team": on_call_team,
            "current_handoff_owner": current_handoff_owner,
            "current_handoff_team": current_handoff_team,
            "preset_code": preset_code,
            "accepted_by": accepted_by,
            "action_batch_id": action_batch_id,
            "acceptance_status": acceptance_status,
            "selection_view_id": selection_view_id,
            "selection_mode": selection_mode,
            "follow_through_status": follow_through_status,
            "action_origin": action_origin,
            "queue_type": queue_type,
            "open_only": open_only,
            "preview_limit": preview_limit,
            "review_limit": review_limit,
            "handoff_limit": handoff_limit,
            "history_limit": history_limit,
            "trend_days": trend_days,
            "forecast_window_days": forecast_window_days,
            "sort_by": sort_by,
        },
        digest_query={
            "vendor_id": vendor_id,
            "responsible_actor": responsible_actor,
            "responsible_team": responsible_team,
            "on_call_owner": on_call_owner,
            "on_call_team": on_call_team,
            "current_handoff_owner": current_handoff_owner,
            "current_handoff_team": current_handoff_team,
            "preset_code": preset_code,
            "accepted_by": accepted_by,
            "action_batch_id": action_batch_id,
            "acceptance_status": acceptance_status,
            "selection_view_id": selection_view_id,
            "selection_mode": selection_mode,
            "follow_through_status": follow_through_status,
            "action_origin": action_origin,
            "queue_type": queue_type,
            "open_only": open_only,
            "preview_limit": preview_limit,
            "review_limit": review_limit,
            "handoff_limit": handoff_limit,
            "history_limit": history_limit,
            "trend_days": trend_days,
            "forecast_window_days": forecast_window_days,
            "sort_by": sort_by,
        },
        history_query={
            "vendor_id": vendor_id,
            "queue_type": queue_type,
            "source_ref": source_ref,
            "on_call_owner": on_call_owner,
            "on_call_team": on_call_team,
        },
        correlation_query={
            "vendor_id": vendor_id,
            "responsible_actor": responsible_actor,
            "responsible_team": responsible_team,
            "queue_type": queue_type,
            "on_call_owner": on_call_owner,
            "on_call_team": on_call_team,
            "trend_days": trend_days,
            "forecast_window_days": forecast_window_days,
        },
        history_limit=history_limit,
        sort_by=sort_by,
    )


def build_governance_review_handoff_acceptance_follow_through_digest_row_urls_bundle(
    *,
    vendor_id: str = "vendor-1",
    responsible_actor: str | None = "qa-reviewer",
    responsible_team: str | None = "governance",
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    current_handoff_owner: str | None = None,
    current_handoff_team: str | None = None,
    accepted_by: str | None = "ops-oncall",
    action_batch_id: str | None = None,
    acceptance_status: str | None = None,
    selection_view_id: str | None = None,
    selection_mode: str | None = None,
    follow_through_status: str | None = None,
    action_origin: str | None = None,
    open_only: bool = False,
    preset_code: str = "critical_triage",
    preview_limit: int = 25,
    review_limit: int = 10,
    handoff_limit: int = 5,
    history_limit: int = 8,
    trend_days: int = 10,
    forecast_window_days: int = 5,
    sort_by: str = "priority",
    queue_type: str = "cleanup_debt",
    source_ref: str = "map-1",
) -> Dict[str, str]:
    return build_governance_review_handoff_history_row_urls(
        handoff_query={
            "vendor_id": vendor_id,
            "responsible_actor": responsible_actor,
            "responsible_team": responsible_team,
            "on_call_owner": on_call_owner,
            "on_call_team": on_call_team,
            "preset_code": preset_code,
            "preview_limit": preview_limit,
            "review_limit": review_limit,
            "handoff_limit": handoff_limit,
            "trend_days": trend_days,
            "forecast_window_days": forecast_window_days,
        },
        acceptance_scope_query={
            "vendor_id": vendor_id,
            "responsible_actor": responsible_actor,
            "responsible_team": responsible_team,
            "on_call_owner": on_call_owner,
            "on_call_team": on_call_team,
            "current_handoff_owner": current_handoff_owner,
            "current_handoff_team": current_handoff_team,
            "preset_code": preset_code,
            "accepted_by": accepted_by,
            "action_batch_id": action_batch_id,
            "acceptance_status": acceptance_status,
            "action_origin": action_origin,
            "queue_type": queue_type,
            "preview_limit": preview_limit,
            "review_limit": review_limit,
            "trend_days": trend_days,
            "forecast_window_days": forecast_window_days,
            "selection_view_id": selection_view_id,
            "selection_mode": selection_mode,
            "follow_through_status": follow_through_status,
            "open_only": open_only,
            "history_limit": history_limit,
            "handoff_limit": handoff_limit,
            "sort_by": sort_by,
        },
        digest_query={
            "vendor_id": vendor_id,
            "responsible_actor": responsible_actor,
            "responsible_team": responsible_team,
            "on_call_owner": on_call_owner,
            "on_call_team": on_call_team,
            "current_handoff_owner": current_handoff_owner,
            "current_handoff_team": current_handoff_team,
            "preset_code": preset_code,
            "accepted_by": accepted_by,
            "action_batch_id": action_batch_id,
            "acceptance_status": acceptance_status,
            "queue_type": queue_type,
            "preview_limit": preview_limit,
            "review_limit": review_limit,
            "handoff_limit": handoff_limit,
            "history_limit": history_limit,
            "trend_days": trend_days,
            "forecast_window_days": forecast_window_days,
            "sort_by": sort_by,
        },
        history_query={
            "vendor_id": vendor_id,
            "queue_type": queue_type,
            "source_ref": source_ref,
            "on_call_owner": on_call_owner,
            "on_call_team": on_call_team,
        },
        correlation_query={
            "vendor_id": vendor_id,
            "responsible_actor": responsible_actor,
            "responsible_team": responsible_team,
            "queue_type": queue_type,
            "on_call_owner": on_call_owner,
            "on_call_team": on_call_team,
            "trend_days": trend_days,
            "forecast_window_days": forecast_window_days,
        },
        history_limit=history_limit,
        sort_by=sort_by,
    )


def build_governance_action_actor_row_urls_bundle(
    *,
    actor: str = "ops-oncall",
    vendor_id: str | None = "vendor-1",
    queue_type: str | None = "rollback_alert",
    action: str | None = "acknowledge",
    team: str | None = None,
    batch_id: str | None = "governance-action-1",
    source_ref: str | None = None,
    open_only: bool = True,
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    include_watch_alerts: bool = True,
    limit: int = 25,
    history_sort_by: str = "recent",
    burndown_sort_by: str = "recent",
    trend_days: int = 10,
    forecast_window_days: int = 5,
) -> Dict[str, str]:
    return build_governance_action_actor_row_urls(
        actor=actor,
        vendor_id=vendor_id,
        queue_type=queue_type,
        action=action,
        team=team,
        batch_id=batch_id,
        source_ref=source_ref,
        open_only=open_only,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        include_watch_alerts=include_watch_alerts,
        limit=limit,
        history_sort_by=history_sort_by,
        burndown_sort_by=burndown_sort_by,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
    )


def build_governance_action_batch_row_urls_bundle(
    *,
    batch_id: str = "governance-action-1",
    vendor_id: str | None = "vendor-1",
    queue_type: str | None = "rollback_alert",
    action: str | None = "acknowledge",
    actor: str | None = "ops-oncall",
    team: str | None = None,
    source_ref: str | None = None,
    open_only: bool = True,
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    include_watch_alerts: bool = True,
    limit: int = 25,
    history_sort_by: str = "recent",
    burndown_sort_by: str = "recent",
    trend_days: int = 10,
    forecast_window_days: int = 5,
) -> Dict[str, str]:
    return build_governance_action_batch_row_urls(
        batch_id=batch_id,
        vendor_id=vendor_id,
        queue_type=queue_type,
        action=action,
        actor=actor,
        team=team,
        source_ref=source_ref,
        open_only=open_only,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        include_watch_alerts=include_watch_alerts,
        limit=limit,
        history_sort_by=history_sort_by,
        burndown_sort_by=burndown_sort_by,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
    )


def build_governance_action_row_urls_bundle(
    *,
    action: str = "assign",
    vendor_id: str | None = "vendor-1",
    queue_type: str | None = None,
    actor: str | None = None,
    team: str | None = None,
    batch_id: str | None = None,
    source_ref: str | None = None,
    open_only: bool = False,
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    include_watch_alerts: bool = True,
    limit: int = 25,
    history_sort_by: str = "recent",
    burndown_sort_by: str = "recent",
    trend_days: int = 10,
    forecast_window_days: int = 5,
) -> Dict[str, str]:
    return build_governance_action_row_urls(
        action=action,
        vendor_id=vendor_id,
        queue_type=queue_type,
        actor=actor,
        team=team,
        batch_id=batch_id,
        source_ref=source_ref,
        open_only=open_only,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        include_watch_alerts=include_watch_alerts,
        limit=limit,
        history_sort_by=history_sort_by,
        burndown_sort_by=burndown_sort_by,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
    )


def build_governance_action_queue_summary_row_urls_bundle(
    *,
    queue_type: str = "rollback_alert",
    vendor_id: str | None = "vendor-1",
    responsible_actor: str | None = None,
    responsible_team: str | None = None,
    include_completed: bool = False,
    include_controlled: bool = True,
    actionable_only: bool = False,
    action: str | None = None,
    actor: str | None = None,
    team: str | None = None,
    batch_id: str | None = None,
    source_ref: str | None = None,
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    include_watch_alerts: bool = True,
    limit: int = 25,
    history_sort_by: str = "recent",
    burndown_sort_by: str = "recent",
    approval_gap_watch_hours: int = 24,
    approval_gap_breach_hours: int = 72,
    cleanup_watch_hours: int = 24,
    cleanup_breach_hours: int = 72,
    rollback_watch_hours: int = 24,
    rollback_breach_hours: int = 72,
    action_watch_hours: int = 24,
    action_stale_hours: int = 72,
    trend_days: int = 10,
    forecast_window_days: int = 5,
) -> Dict[str, str]:
    return build_governance_action_queue_summary_row_urls(
        queue_type=queue_type,
        vendor_id=vendor_id,
        responsible_actor=responsible_actor,
        responsible_team=responsible_team,
        include_completed=include_completed,
        include_controlled=include_controlled,
        actionable_only=actionable_only,
        action=action,
        actor=actor,
        team=team,
        batch_id=batch_id,
        source_ref=source_ref,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        include_watch_alerts=include_watch_alerts,
        limit=limit,
        history_sort_by=history_sort_by,
        burndown_sort_by=burndown_sort_by,
        approval_gap_watch_hours=approval_gap_watch_hours,
        approval_gap_breach_hours=approval_gap_breach_hours,
        cleanup_watch_hours=cleanup_watch_hours,
        cleanup_breach_hours=cleanup_breach_hours,
        rollback_watch_hours=rollback_watch_hours,
        rollback_breach_hours=rollback_breach_hours,
        action_watch_hours=action_watch_hours,
        action_stale_hours=action_stale_hours,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
    )


def build_governance_review_handoff_acceptance_actor_row_urls_bundle(
    *,
    accepted_by: str = "ops-oncall",
    vendor_id: str | None = "vendor-1",
    responsible_actor: str | None = "qa-reviewer",
    responsible_team: str | None = "governance",
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    current_handoff_owner: str | None = None,
    current_handoff_team: str | None = None,
    preset_code: str | None = "critical_triage",
    action_batch_id: str | None = None,
    acceptance_action: str | None = None,
    acceptance_status: str | None = None,
    selection_view_id: str | None = None,
    selection_mode: str | None = None,
    follow_through_status: str | None = None,
    action_origin: str | None = None,
    queue_type: str | None = None,
    open_only: bool = False,
    activity_date: str | None = None,
    activity_kind: str | None = None,
    preview_limit: int = 25,
    review_limit: int = 10,
    handoff_limit: int = 5,
    history_limit: int = 8,
    trend_days: int = 10,
    forecast_window_days: int = 5,
    sort_by: str = "priority",
) -> Dict[str, str]:
    return build_governance_review_handoff_acceptance_actor_row_urls(
        accepted_by=accepted_by,
        vendor_id=vendor_id,
        responsible_actor=responsible_actor,
        responsible_team=responsible_team,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        current_handoff_owner=current_handoff_owner,
        current_handoff_team=current_handoff_team,
        preset_code=preset_code,
        action_batch_id=action_batch_id,
        acceptance_action=acceptance_action,
        acceptance_status=acceptance_status,
        selection_view_id=selection_view_id,
        selection_mode=selection_mode,
        follow_through_status=follow_through_status,
        action_origin=action_origin,
        queue_type=queue_type,
        open_only=open_only,
        activity_date=activity_date,
        activity_kind=activity_kind,
        preview_limit=preview_limit,
        review_limit=review_limit,
        handoff_limit=handoff_limit,
        history_limit=history_limit,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
        sort_by=sort_by,
    )


def build_governance_review_handoff_acceptance_queue_row_urls_bundle(
    *,
    queue_type: str = "cleanup_debt",
    vendor_id: str | None = "vendor-1",
    responsible_actor: str | None = "qa-reviewer",
    responsible_team: str | None = "governance",
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    current_handoff_owner: str | None = None,
    current_handoff_team: str | None = None,
    preset_code: str | None = "critical_triage",
    accepted_by: str | None = "ops-oncall",
    action_batch_id: str | None = None,
    acceptance_action: str | None = None,
    acceptance_status: str | None = None,
    selection_view_id: str | None = None,
    selection_mode: str | None = None,
    follow_through_status: str | None = None,
    action_origin: str | None = None,
    open_only: bool = False,
    activity_date: str | None = None,
    activity_kind: str | None = None,
    preview_limit: int = 25,
    review_limit: int = 10,
    handoff_limit: int = 5,
    history_limit: int = 8,
    trend_days: int = 10,
    forecast_window_days: int = 5,
    sort_by: str = "priority",
) -> Dict[str, str]:
    return build_governance_review_handoff_acceptance_queue_row_urls(
        queue_type=queue_type,
        vendor_id=vendor_id,
        responsible_actor=responsible_actor,
        responsible_team=responsible_team,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        current_handoff_owner=current_handoff_owner,
        current_handoff_team=current_handoff_team,
        preset_code=preset_code,
        accepted_by=accepted_by,
        action_batch_id=action_batch_id,
        acceptance_action=acceptance_action,
        acceptance_status=acceptance_status,
        selection_view_id=selection_view_id,
        selection_mode=selection_mode,
        follow_through_status=follow_through_status,
        action_origin=action_origin,
        open_only=open_only,
        activity_date=activity_date,
        activity_kind=activity_kind,
        preview_limit=preview_limit,
        review_limit=review_limit,
        handoff_limit=handoff_limit,
        history_limit=history_limit,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
        sort_by=sort_by,
    )


def build_governance_responsibility_actor_summary_row_urls_bundle(
    *,
    responsible_actor: str = "qa-reviewer",
    vendor_id: str | None = "vendor-1",
    responsible_team: str | None = "governance",
    queue_type: str | None = None,
    include_completed: bool = False,
    include_controlled: bool = True,
    actionable_only: bool = False,
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    include_watch_alerts: bool = True,
    limit: int = 25,
    inbox_sort_by: str = "priority",
    correlation_sort_by: str = "priority",
    approval_gap_watch_hours: int = 24,
    approval_gap_breach_hours: int = 72,
    cleanup_watch_hours: int = 24,
    cleanup_breach_hours: int = 72,
    rollback_watch_hours: int = 24,
    rollback_breach_hours: int = 72,
    action_watch_hours: int = 24,
    action_stale_hours: int = 72,
    trend_days: int = 10,
    forecast_window_days: int = 5,
) -> Dict[str, str]:
    return build_governance_responsibility_actor_summary_row_urls(
        responsible_actor=responsible_actor,
        vendor_id=vendor_id,
        responsible_team=responsible_team,
        queue_type=queue_type,
        include_completed=include_completed,
        include_controlled=include_controlled,
        actionable_only=actionable_only,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        include_watch_alerts=include_watch_alerts,
        limit=limit,
        inbox_sort_by=inbox_sort_by,
        correlation_sort_by=correlation_sort_by,
        approval_gap_watch_hours=approval_gap_watch_hours,
        approval_gap_breach_hours=approval_gap_breach_hours,
        cleanup_watch_hours=cleanup_watch_hours,
        cleanup_breach_hours=cleanup_breach_hours,
        rollback_watch_hours=rollback_watch_hours,
        rollback_breach_hours=rollback_breach_hours,
        action_watch_hours=action_watch_hours,
        action_stale_hours=action_stale_hours,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
    )


def build_governance_responsibility_team_summary_row_urls_bundle(
    *,
    responsible_team: str = "governance",
    vendor_id: str | None = "vendor-1",
    responsible_actor: str | None = None,
    queue_type: str | None = None,
    include_completed: bool = False,
    include_controlled: bool = True,
    actionable_only: bool = False,
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    include_watch_alerts: bool = True,
    limit: int = 25,
    inbox_sort_by: str = "priority",
    correlation_sort_by: str = "priority",
    approval_gap_watch_hours: int = 24,
    approval_gap_breach_hours: int = 72,
    cleanup_watch_hours: int = 24,
    cleanup_breach_hours: int = 72,
    rollback_watch_hours: int = 24,
    rollback_breach_hours: int = 72,
    action_watch_hours: int = 24,
    action_stale_hours: int = 72,
    trend_days: int = 10,
    forecast_window_days: int = 5,
) -> Dict[str, str]:
    return build_governance_responsibility_team_summary_row_urls(
        responsible_team=responsible_team,
        vendor_id=vendor_id,
        responsible_actor=responsible_actor,
        queue_type=queue_type,
        include_completed=include_completed,
        include_controlled=include_controlled,
        actionable_only=actionable_only,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        include_watch_alerts=include_watch_alerts,
        limit=limit,
        inbox_sort_by=inbox_sort_by,
        correlation_sort_by=correlation_sort_by,
        approval_gap_watch_hours=approval_gap_watch_hours,
        approval_gap_breach_hours=approval_gap_breach_hours,
        cleanup_watch_hours=cleanup_watch_hours,
        cleanup_breach_hours=cleanup_breach_hours,
        rollback_watch_hours=rollback_watch_hours,
        rollback_breach_hours=rollback_breach_hours,
        action_watch_hours=action_watch_hours,
        action_stale_hours=action_stale_hours,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
    )


def build_governance_review_handoff_acceptance_entry_efficiency_row_urls_bundle(
    *,
    vendor_id: str | None = "vendor-1",
    responsible_actor: str | None = None,
    responsible_team: str | None = None,
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    preset_code: str | None = "rollback_on_call",
    accepted_by: str | None = None,
    action_batch_id: str | None = None,
    acceptance_status: str | None = None,
    selection_view_id: str | None = "handoff-board",
    selection_mode: str | None = "source_refs",
    follow_through_status: str | None = "open_follow_through",
    action_origin: str | None = "review_handoff_acceptance",
    queue_type: str | None = None,
    open_only: bool = True,
    preview_limit: int = 25,
    review_limit: int = 10,
    handoff_limit: int = 5,
    history_limit: int = 8,
    trend_days: int = 10,
    forecast_window_days: int = 5,
    sort_by: str = "recent",
) -> Dict[str, str]:
    return build_governance_review_handoff_acceptance_entry_efficiency_row_urls(
        vendor_id=vendor_id,
        responsible_actor=responsible_actor,
        responsible_team=responsible_team,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        preset_code=preset_code,
        accepted_by=accepted_by,
        action_batch_id=action_batch_id,
        acceptance_status=acceptance_status,
        selection_view_id=selection_view_id,
        selection_mode=selection_mode,
        follow_through_status=follow_through_status,
        action_origin=action_origin,
        queue_type=queue_type,
        open_only=open_only,
        preview_limit=preview_limit,
        review_limit=review_limit,
        handoff_limit=handoff_limit,
        history_limit=history_limit,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
        sort_by=sort_by,
    )


def build_governance_review_handoff_acceptance_selection_mode_row_urls_bundle(
    *,
    selection_mode: str = "source_refs",
    vendor_id: str | None = "vendor-1",
    responsible_actor: str | None = None,
    responsible_team: str | None = None,
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    current_handoff_owner: str | None = None,
    current_handoff_team: str | None = None,
    preset_code: str | None = "rollback_on_call",
    accepted_by: str | None = None,
    action_batch_id: str | None = None,
    acceptance_action: str | None = None,
    acceptance_status: str | None = None,
    selection_view_id: str | None = "handoff-board",
    follow_through_status: str | None = "open_follow_through",
    action_origin: str | None = "review_handoff_acceptance",
    queue_type: str | None = None,
    open_only: bool = True,
    activity_date: str | None = None,
    activity_kind: str | None = None,
    preview_limit: int = 25,
    review_limit: int = 10,
    handoff_limit: int = 5,
    history_limit: int = 8,
    trend_days: int = 10,
    forecast_window_days: int = 5,
    sort_by: str = "recent",
) -> Dict[str, str]:
    return build_governance_review_handoff_acceptance_selection_mode_row_urls(
        selection_mode=selection_mode,
        vendor_id=vendor_id,
        responsible_actor=responsible_actor,
        responsible_team=responsible_team,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        current_handoff_owner=current_handoff_owner,
        current_handoff_team=current_handoff_team,
        preset_code=preset_code,
        accepted_by=accepted_by,
        action_batch_id=action_batch_id,
        acceptance_action=acceptance_action,
        acceptance_status=acceptance_status,
        selection_view_id=selection_view_id,
        follow_through_status=follow_through_status,
        action_origin=action_origin,
        queue_type=queue_type,
        open_only=open_only,
        activity_date=activity_date,
        activity_kind=activity_kind,
        preview_limit=preview_limit,
        review_limit=review_limit,
        handoff_limit=handoff_limit,
        history_limit=history_limit,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
        sort_by=sort_by,
    )


def build_governance_review_handoff_acceptance_action_row_urls_bundle(
    *,
    acceptance_action: str = "acknowledge",
    vendor_id: str | None = "vendor-1",
    responsible_actor: str | None = None,
    responsible_team: str | None = None,
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    current_handoff_owner: str | None = None,
    current_handoff_team: str | None = None,
    preset_code: str | None = "rollback_on_call",
    accepted_by: str | None = None,
    action_batch_id: str | None = None,
    acceptance_status: str | None = None,
    selection_view_id: str | None = "handoff-board",
    selection_mode: str | None = "source_refs",
    follow_through_status: str | None = "open_follow_through",
    action_origin: str | None = "review_handoff_acceptance",
    queue_type: str | None = None,
    open_only: bool = True,
    activity_date: str | None = None,
    activity_kind: str | None = None,
    preview_limit: int = 25,
    review_limit: int = 10,
    handoff_limit: int = 5,
    history_limit: int = 8,
    trend_days: int = 10,
    forecast_window_days: int = 5,
    sort_by: str = "recent",
) -> Dict[str, str]:
    return build_governance_review_handoff_acceptance_action_row_urls(
        acceptance_action=acceptance_action,
        vendor_id=vendor_id,
        responsible_actor=responsible_actor,
        responsible_team=responsible_team,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        current_handoff_owner=current_handoff_owner,
        current_handoff_team=current_handoff_team,
        preset_code=preset_code,
        accepted_by=accepted_by,
        action_batch_id=action_batch_id,
        acceptance_status=acceptance_status,
        selection_view_id=selection_view_id,
        selection_mode=selection_mode,
        follow_through_status=follow_through_status,
        action_origin=action_origin,
        queue_type=queue_type,
        open_only=open_only,
        activity_date=activity_date,
        activity_kind=activity_kind,
        preview_limit=preview_limit,
        review_limit=review_limit,
        handoff_limit=handoff_limit,
        history_limit=history_limit,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
        sort_by=sort_by,
    )


def build_governance_review_handoff_acceptance_follow_through_status_row_urls_bundle(
    *,
    follow_through_status: str = "open_follow_through",
    vendor_id: str | None = "vendor-1",
    responsible_actor: str | None = None,
    responsible_team: str | None = None,
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    current_handoff_owner: str | None = None,
    current_handoff_team: str | None = None,
    preset_code: str | None = "rollback_on_call",
    accepted_by: str | None = None,
    action_batch_id: str | None = None,
    acceptance_action: str | None = None,
    acceptance_status: str | None = None,
    selection_view_id: str | None = "handoff-board",
    selection_mode: str | None = "source_refs",
    action_origin: str | None = "review_handoff_acceptance",
    queue_type: str | None = None,
    open_only: bool = True,
    activity_date: str | None = None,
    activity_kind: str | None = None,
    preview_limit: int = 25,
    review_limit: int = 10,
    handoff_limit: int = 5,
    history_limit: int = 8,
    trend_days: int = 10,
    forecast_window_days: int = 5,
    sort_by: str = "recent",
) -> Dict[str, str]:
    return build_governance_review_handoff_acceptance_follow_through_status_row_urls(
        follow_through_status=follow_through_status,
        vendor_id=vendor_id,
        responsible_actor=responsible_actor,
        responsible_team=responsible_team,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        current_handoff_owner=current_handoff_owner,
        current_handoff_team=current_handoff_team,
        preset_code=preset_code,
        accepted_by=accepted_by,
        action_batch_id=action_batch_id,
        acceptance_action=acceptance_action,
        acceptance_status=acceptance_status,
        selection_view_id=selection_view_id,
        selection_mode=selection_mode,
        action_origin=action_origin,
        queue_type=queue_type,
        open_only=open_only,
        activity_date=activity_date,
        activity_kind=activity_kind,
        preview_limit=preview_limit,
        review_limit=review_limit,
        handoff_limit=handoff_limit,
        history_limit=history_limit,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
        sort_by=sort_by,
    )


def build_governance_review_handoff_acceptance_entry_efficiency_snapshot_urls_bundle(
    *,
    vendor_id: str | None = "vendor-1",
    responsible_actor: str | None = None,
    responsible_team: str | None = None,
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    current_handoff_owner: str | None = None,
    current_handoff_team: str | None = None,
    preset_code: str | None = "rollback_on_call",
    accepted_by: str | None = None,
    action_batch_id: str | None = None,
    acceptance_status: str | None = None,
    selection_view_id: str | None = "handoff-board",
    selection_mode: str | None = "source_refs",
    follow_through_status: str | None = "open_follow_through",
    action_origin: str | None = None,
    queue_type: str | None = None,
    open_only: bool = True,
    preview_limit: int = 25,
    review_limit: int = 10,
    handoff_limit: int = 5,
    history_limit: int = 8,
    trend_days: int = 10,
    forecast_window_days: int = 5,
    sort_by: str = "recent",
) -> Dict[str, str]:
    return build_governance_review_handoff_acceptance_entry_efficiency_snapshot_urls(
        vendor_id=vendor_id,
        responsible_actor=responsible_actor,
        responsible_team=responsible_team,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        current_handoff_owner=current_handoff_owner,
        current_handoff_team=current_handoff_team,
        preset_code=preset_code,
        accepted_by=accepted_by,
        action_batch_id=action_batch_id,
        acceptance_status=acceptance_status,
        selection_view_id=selection_view_id,
        selection_mode=selection_mode,
        follow_through_status=follow_through_status,
        action_origin=action_origin,
        queue_type=queue_type,
        open_only=open_only,
        preview_limit=preview_limit,
        review_limit=review_limit,
        handoff_limit=handoff_limit,
        history_limit=history_limit,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
        sort_by=sort_by,
    )


def build_governance_review_handoff_acceptance_follow_through_owner_row_urls_bundle(
    *,
    current_handoff_owner: str = "ops-reviewer",
    vendor_id: str | None = "vendor-1",
    responsible_actor: str | None = "qa-reviewer",
    responsible_team: str | None = "governance",
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    current_handoff_team: str | None = None,
    preset_code: str | None = "critical_triage",
    accepted_by: str | None = None,
    action_batch_id: str | None = None,
    acceptance_status: str | None = None,
    selection_view_id: str | None = None,
    selection_mode: str | None = None,
    follow_through_status: str | None = None,
    action_origin: str | None = None,
    queue_type: str | None = None,
    open_only: bool = False,
    activity_date: str | None = None,
    activity_kind: str | None = None,
    preview_limit: int = 25,
    review_limit: int = 10,
    handoff_limit: int = 5,
    history_limit: int = 8,
    trend_days: int = 10,
    forecast_window_days: int = 5,
    sort_by: str = "priority",
) -> Dict[str, str]:
    return build_governance_review_handoff_acceptance_follow_through_owner_row_urls(
        current_handoff_owner=current_handoff_owner,
        vendor_id=vendor_id,
        responsible_actor=responsible_actor,
        responsible_team=responsible_team,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        current_handoff_team=current_handoff_team,
        preset_code=preset_code,
        accepted_by=accepted_by,
        action_batch_id=action_batch_id,
        acceptance_status=acceptance_status,
        selection_view_id=selection_view_id,
        selection_mode=selection_mode,
        follow_through_status=follow_through_status,
        action_origin=action_origin,
        queue_type=queue_type,
        open_only=open_only,
        activity_date=activity_date,
        activity_kind=activity_kind,
        preview_limit=preview_limit,
        review_limit=review_limit,
        handoff_limit=handoff_limit,
        history_limit=history_limit,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
        sort_by=sort_by,
    )


def build_governance_review_handoff_acceptance_follow_through_view_row_urls_bundle(
    *,
    selection_view_id: str | None = "handoff-board",
    vendor_id: str | None = "vendor-1",
    responsible_actor: str | None = "qa-reviewer",
    responsible_team: str | None = "governance",
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    current_handoff_owner: str | None = "ops-reviewer",
    current_handoff_team: str | None = "governance",
    preset_code: str | None = "critical_triage",
    accepted_by: str | None = "ops-oncall",
    action_batch_id: str | None = None,
    selection_mode: str | None = "source_refs",
    follow_through_status: str | None = "open_follow_through",
    action_origin: str | None = None,
    queue_type: str | None = None,
    open_only: bool = True,
    activity_date: str | None = "2026-03-24",
    activity_kind: str | None = "opened",
    preview_limit: int = 25,
    review_limit: int = 10,
    handoff_limit: int = 5,
    history_limit: int = 8,
    trend_days: int = 10,
    forecast_window_days: int = 5,
    sort_by: str = "priority",
) -> Dict[str, str]:
    assert selection_view_id is not None
    return build_governance_review_handoff_acceptance_follow_through_view_row_urls(
        selection_view_id=selection_view_id,
        vendor_id=vendor_id,
        responsible_actor=responsible_actor,
        responsible_team=responsible_team,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        current_handoff_owner=current_handoff_owner,
        current_handoff_team=current_handoff_team,
        preset_code=preset_code,
        accepted_by=accepted_by,
        action_batch_id=action_batch_id,
        selection_mode=selection_mode,
        follow_through_status=follow_through_status,
        action_origin=action_origin,
        queue_type=queue_type,
        open_only=open_only,
        activity_date=activity_date,
        activity_kind=activity_kind,
        preview_limit=preview_limit,
        review_limit=review_limit,
        handoff_limit=handoff_limit,
        history_limit=history_limit,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
        sort_by=sort_by,
    )


def build_governance_review_handoff_acceptance_follow_through_batch_row_urls_bundle(
    *,
    action_batch_id: str = "governance-action-1",
    vendor_id: str | None = "vendor-1",
    responsible_actor: str | None = "qa-reviewer",
    responsible_team: str | None = "governance",
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    current_handoff_owner: str | None = "ops-reviewer",
    current_handoff_team: str | None = "governance",
    preset_code: str | None = "critical_triage",
    accepted_by: str | None = "ops-oncall",
    selection_view_id: str | None = "handoff-board",
    selection_mode: str | None = "source_refs",
    follow_through_status: str | None = "open_follow_through",
    action_origin: str | None = None,
    queue_type: str | None = None,
    open_only: bool = True,
    activity_date: str | None = "2026-03-24",
    activity_kind: str | None = "opened",
    preview_limit: int = 25,
    review_limit: int = 10,
    handoff_limit: int = 5,
    history_limit: int = 8,
    trend_days: int = 10,
    forecast_window_days: int = 5,
    sort_by: str = "priority",
) -> Dict[str, str]:
    return build_governance_review_handoff_acceptance_follow_through_batch_row_urls(
        action_batch_id=action_batch_id,
        vendor_id=vendor_id,
        responsible_actor=responsible_actor,
        responsible_team=responsible_team,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        current_handoff_owner=current_handoff_owner,
        current_handoff_team=current_handoff_team,
        preset_code=preset_code,
        accepted_by=accepted_by,
        selection_view_id=selection_view_id,
        selection_mode=selection_mode,
        follow_through_status=follow_through_status,
        action_origin=action_origin,
        queue_type=queue_type,
        open_only=open_only,
        activity_date=activity_date,
        activity_kind=activity_kind,
        preview_limit=preview_limit,
        review_limit=review_limit,
        handoff_limit=handoff_limit,
        history_limit=history_limit,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
        sort_by=sort_by,
    )


def build_governance_review_handoff_acceptance_trend_row_urls_bundle(
    *,
    activity_date: str = "2026-03-24",
    vendor_id: str | None = "vendor-1",
    responsible_actor: str | None = "qa-reviewer",
    responsible_team: str | None = "governance",
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    preset_code: str | None = "critical_triage",
    accepted_by: str | None = None,
    action_batch_id: str | None = None,
    acceptance_action: str | None = None,
    acceptance_status: str | None = None,
    selection_view_id: str | None = None,
    selection_mode: str | None = None,
    follow_through_status: str | None = None,
    action_origin: str | None = None,
    queue_type: str | None = None,
    open_only: bool = False,
    preview_limit: int = 25,
    review_limit: int = 10,
    handoff_limit: int = 5,
    history_limit: int = 8,
    trend_days: int = 10,
    forecast_window_days: int = 5,
    sort_by: str = "priority",
) -> Dict[str, str]:
    return build_governance_review_handoff_acceptance_trend_row_urls(
        activity_date=activity_date,
        vendor_id=vendor_id,
        responsible_actor=responsible_actor,
        responsible_team=responsible_team,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        preset_code=preset_code,
        accepted_by=accepted_by,
        action_batch_id=action_batch_id,
        acceptance_action=acceptance_action,
        acceptance_status=acceptance_status,
        selection_view_id=selection_view_id,
        selection_mode=selection_mode,
        follow_through_status=follow_through_status,
        action_origin=action_origin,
        queue_type=queue_type,
        open_only=open_only,
        preview_limit=preview_limit,
        review_limit=review_limit,
        handoff_limit=handoff_limit,
        history_limit=history_limit,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
        sort_by=sort_by,
    )


def build_governance_review_handoff_acceptance_status_row_urls_bundle(
    *,
    acceptance_status: str = "pending_acceptance",
    vendor_id: str | None = "vendor-1",
    responsible_actor: str | None = "qa-reviewer",
    responsible_team: str | None = "governance",
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    current_handoff_owner: str | None = None,
    current_handoff_team: str | None = None,
    preset_code: str | None = "critical_triage",
    accepted_by: str | None = "ops-oncall",
    action_batch_id: str | None = None,
    acceptance_action: str | None = None,
    selection_view_id: str | None = None,
    selection_mode: str | None = None,
    follow_through_status: str | None = None,
    action_origin: str | None = None,
    queue_type: str | None = None,
    open_only: bool = False,
    activity_date: str | None = None,
    activity_kind: str | None = None,
    preview_limit: int = 25,
    review_limit: int = 10,
    handoff_limit: int = 5,
    history_limit: int = 8,
    trend_days: int = 10,
    forecast_window_days: int = 5,
    sort_by: str = "priority",
) -> Dict[str, str]:
    return build_governance_review_handoff_acceptance_status_row_urls(
        acceptance_status=acceptance_status,
        vendor_id=vendor_id,
        responsible_actor=responsible_actor,
        responsible_team=responsible_team,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        current_handoff_owner=current_handoff_owner,
        current_handoff_team=current_handoff_team,
        preset_code=preset_code,
        accepted_by=accepted_by,
        action_batch_id=action_batch_id,
        acceptance_action=acceptance_action,
        selection_view_id=selection_view_id,
        selection_mode=selection_mode,
        follow_through_status=follow_through_status,
        action_origin=action_origin,
        queue_type=queue_type,
        open_only=open_only,
        activity_date=activity_date,
        activity_kind=activity_kind,
        preview_limit=preview_limit,
        review_limit=review_limit,
        handoff_limit=handoff_limit,
        history_limit=history_limit,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
        sort_by=sort_by,
    )


def build_governance_review_handoff_acceptance_follow_through_trend_row_urls_bundle(
    *,
    activity_date: str = "2026-03-24",
    vendor_id: str | None = "vendor-1",
    responsible_actor: str | None = "qa-reviewer",
    responsible_team: str | None = "governance",
    on_call_owner: str | None = "ops-oncall",
    on_call_team: str | None = None,
    preset_code: str | None = "critical_triage",
    accepted_by: str | None = None,
    action_batch_id: str | None = None,
    acceptance_status: str | None = None,
    selection_view_id: str | None = None,
    selection_mode: str | None = None,
    follow_through_status: str | None = None,
    action_origin: str | None = None,
    queue_type: str | None = None,
    open_only: bool = False,
    preview_limit: int = 25,
    review_limit: int = 10,
    handoff_limit: int = 5,
    history_limit: int = 8,
    trend_days: int = 10,
    forecast_window_days: int = 5,
    sort_by: str = "priority",
) -> Dict[str, str]:
    return build_governance_review_handoff_acceptance_follow_through_trend_row_urls(
        activity_date=activity_date,
        vendor_id=vendor_id,
        responsible_actor=responsible_actor,
        responsible_team=responsible_team,
        on_call_owner=on_call_owner,
        on_call_team=on_call_team,
        preset_code=preset_code,
        accepted_by=accepted_by,
        action_batch_id=action_batch_id,
        acceptance_status=acceptance_status,
        selection_view_id=selection_view_id,
        selection_mode=selection_mode,
        follow_through_status=follow_through_status,
        action_origin=action_origin,
        queue_type=queue_type,
        open_only=open_only,
        preview_limit=preview_limit,
        review_limit=review_limit,
        handoff_limit=handoff_limit,
        history_limit=history_limit,
        trend_days=trend_days,
        forecast_window_days=forecast_window_days,
        sort_by=sort_by,
    )
