"""Deterministic generator for the initial tenant baseline Alembic revision.

This is a one-shot dev tool. It is NOT loaded at runtime. It reads
SQLAlchemy metadata via `yuantus.scripts.tenant_schema.build_tenant_metadata()`,
strips foreign-key constraints whose target lives in
``GLOBAL_TABLE_NAMES`` (preserving the column itself), and renders an
Alembic revision file via Alembic's `produce_migrations` machinery
against the PostgreSQL dialect.

The output is written to::

    migrations_tenant/versions/t1_initial_tenant_baseline.py

The revision file is what gets committed and reviewed; this generator
is committed only so the same baseline can be re-derived if SQLAlchemy
or the model layer changes upstream. Re-running this generator on
unchanged metadata produces byte-identical output (asserted by
`test_tenant_baseline_revision.test_generator_output_is_deterministic`).

Usage::

    PYTHONPATH=src python scripts/generate_tenant_baseline.py [--check]

With ``--check``, the generator regenerates the revision in memory and
exits non-zero if it differs from the committed file (CI guard).
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from sqlalchemy import ForeignKeyConstraint, MetaData
from sqlalchemy.dialects import postgresql

from alembic.autogenerate import render_python_code
from alembic.operations.ops import (
    CreateIndexOp,
    CreateTableOp,
    DowngradeOps,
    DropIndexOp,
    DropTableOp,
    UpgradeOps,
)
from alembic.runtime.migration import MigrationContext

from yuantus.scripts.tenant_schema import GLOBAL_TABLE_NAMES, build_tenant_metadata


REVISION_ID = "t1_initial_tenant_baseline"
REVISION_FILENAME = f"{REVISION_ID}.py"


def _strip_cross_schema_fks(metadata: MetaData) -> int:
    """Drop FK constraints whose target lives in ``GLOBAL_TABLE_NAMES``.

    Mutates ``metadata`` in place. Columns themselves are preserved (without
    the FK constraint), which lets tenant tables retain user-attribution
    columns like ``created_by_id`` even though the global ``rbac_users`` /
    ``users`` tables are not part of the tenant schema. Returns the number
    of stripped FK constraints (for verification).
    """
    stripped = 0
    for table in metadata.tables.values():
        to_remove: list[ForeignKeyConstraint] = []
        for cons in list(table.constraints):
            if not isinstance(cons, ForeignKeyConstraint):
                continue
            for elem in cons.elements:
                target_table = elem.target_fullname.split(".", 1)[0]
                if target_table in GLOBAL_TABLE_NAMES:
                    to_remove.append(cons)
                    break
        for cons in to_remove:
            for elem in list(cons.elements):
                if elem.parent is not None:
                    elem.parent.foreign_keys.discard(elem)
                table.foreign_keys.discard(elem)
            table.constraints.discard(cons)
            stripped += 1
    return stripped


def _build_ops(metadata: MetaData) -> tuple[UpgradeOps, DowngradeOps]:
    """Build deterministic UpgradeOps / DowngradeOps from metadata."""
    tables = list(metadata.sorted_tables)
    create_table_ops = [CreateTableOp.from_table(t) for t in tables]
    create_index_ops = [
        CreateIndexOp.from_index(idx)
        for t in tables
        for idx in sorted(t.indexes, key=lambda i: (i.name or "", tuple(c.name for c in i.columns)))
    ]
    upgrade_ops = UpgradeOps(ops=create_table_ops + create_index_ops)
    drop_index_ops = [
        DropIndexOp.from_index(idx)
        for t in reversed(tables)
        for idx in sorted(
            t.indexes,
            key=lambda i: (i.name or "", tuple(c.name for c in i.columns)),
            reverse=True,
        )
    ]
    drop_table_ops = [DropTableOp(t.name) for t in reversed(tables)]
    downgrade_ops = DowngradeOps(ops=drop_index_ops + drop_table_ops)
    return upgrade_ops, downgrade_ops


_BODY_PATTERNS_TO_STRIP = (
    re.compile(r"^\s*# ### commands auto generated by Alembic.*?###$", re.MULTILINE),
    re.compile(r"^\s*# ### end Alembic commands ###$", re.MULTILINE),
)


def _clean_body(rendered: str) -> str:
    cleaned = rendered
    for pattern in _BODY_PATTERNS_TO_STRIP:
        cleaned = pattern.sub("", cleaned)
    return "\n".join(line for line in cleaned.splitlines() if line.strip())


def _build_revision_file(upgrade_body: str, downgrade_body: str) -> str:
    has_postgresql_types = "postgresql." in upgrade_body or "postgresql." in downgrade_body
    pg_import = "from sqlalchemy.dialects import postgresql\n" if has_postgresql_types else ""
    return (
        '"""Initial tenant baseline.\n'
        "\n"
        "P3.3.3: deterministic SQLAlchemy-metadata-derived baseline created via\n"
        "scripts/generate_tenant_baseline.py against the PostgreSQL dialect.\n"
        "Cross-schema foreign keys (targeting GLOBAL_TABLE_NAMES tables such as\n"
        "rbac_users, users) are stripped — the columns are preserved without\n"
        "the FK constraint because the referenced global tables live in a\n"
        "separate identity-plane schema.\n"
        "\n"
        f"Revision ID: {REVISION_ID}\n"
        "Revises: \n"
        '"""\n'
        "from __future__ import annotations\n"
        "\n"
        "from typing import Sequence, Union\n"
        "\n"
        "from alembic import op\n"
        "import sqlalchemy as sa\n"
        f"{pg_import}"
        "\n"
        "\n"
        "# revision identifiers, used by Alembic.\n"
        f'revision: str = "{REVISION_ID}"\n'
        "down_revision: Union[str, None] = None\n"
        "branch_labels: Union[str, Sequence[str], None] = None\n"
        "depends_on: Union[str, Sequence[str], None] = None\n"
        "\n"
        "\n"
        "def upgrade() -> None:\n"
        f"{upgrade_body}\n"
        "\n"
        "\n"
        "def downgrade() -> None:\n"
        f"{downgrade_body}\n"
    )


def generate() -> str:
    """Build the full revision file content (deterministic)."""
    metadata = build_tenant_metadata()
    _strip_cross_schema_fks(metadata)
    upgrade_ops, downgrade_ops = _build_ops(metadata)
    mc = MigrationContext.configure(dialect=postgresql.dialect())
    upgrade_body = _clean_body(render_python_code(upgrade_ops, migration_context=mc))
    downgrade_body = _clean_body(render_python_code(downgrade_ops, migration_context=mc))
    return _build_revision_file(upgrade_body, downgrade_body)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the committed revision file matches what would be generated; exit 1 on drift.",
    )
    args = parser.parse_args(argv)

    repo_root = Path(__file__).resolve().parent.parent
    target = repo_root / "migrations_tenant" / "versions" / REVISION_FILENAME
    content = generate()
    if args.check:
        if not target.exists():
            print(f"missing: {target}", file=sys.stderr)
            return 1
        existing = target.read_text()
        if existing != content:
            print(f"drift: {target} differs from generator output", file=sys.stderr)
            return 1
        print("ok: committed revision matches generator output")
        return 0
    target.write_text(content)
    print(f"wrote {target} ({len(content)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
