#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  scripts/generate_tenant_import_rehearsal_env_template.sh [--out PATH] [--force]

Options:
  --out PATH  Output env-file path.
              Default: $HOME/.config/yuantus/tenant-import-rehearsal.env
  --force     Overwrite an existing output file.
  -h, --help  Show this help.

Generate a repo-external P3.4 tenant import rehearsal env-file template for
scripts/run_tenant_import_rehearsal_full_closeout.sh --env-file.

The generated file contains placeholders only. Fill it with real non-production
PostgreSQL DSNs outside the repository. The script sets mode 0600 and does not print database URL values.
USAGE
}

out="${HOME}/.config/yuantus/tenant-import-rehearsal.env"
force=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --out)
      out="${2:?missing value for --out}"
      shift 2
      ;;
    --force)
      force=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "error: unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -e "$out" && "$force" -ne 1 ]]; then
  echo "error: output already exists; pass --force to overwrite: $out" >&2
  exit 2
fi

mkdir -p "$(dirname "$out")"
tmp="${out}.tmp.$$"
umask 077
cat > "$tmp" <<'EOF'
# Generated by scripts/generate_tenant_import_rehearsal_env_template.sh
# Contains non-production database URLs after operator edits.
# Keep this file outside the repository. Do not commit.

SOURCE_DATABASE_URL='postgresql://source-user:REPLACE_ME@source-host/source-db'
TARGET_DATABASE_URL='postgresql://target-user:REPLACE_ME@target-host/target-db'
EOF
chmod 600 "$tmp"
mv "$tmp" "$out"

cat <<EOF
Generated P3.4 tenant import rehearsal env-file template.

Env file:
  $out

Next steps:
  1. Edit the file locally and replace both REPLACE_ME placeholders with real non-production DSN values.
  2. Run:
       scripts/run_tenant_import_rehearsal_full_closeout.sh --env-file "$out" ...

This script generated placeholders only and did not print database URL values.
EOF
