#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  scripts/generate_p2_shared_dev_bootstrap_env.sh [options]

Options:
  --bootstrap-out <path>    Output path for the server-side bootstrap env file
                            default: $HOME/.config/yuantus/bootstrap/shared-dev.bootstrap.env
  --observation-out <path>  Output path for the operator-side observation env file
                            default: $HOME/.config/yuantus/p2-shared-dev.env
  --base-url <url>          BASE_URL for the observation env
                            default: https://<shared-dev-host>
  --tenant-id <id>          default: tenant-1
  --org-id <id>             default: org-1
  --admin-username <name>   default: admin
  --viewer-username <name>  default: ops-viewer
  --admin-password <pwd>    Optional override; otherwise a random password is generated
  --viewer-password <pwd>   Optional override; otherwise a random password is generated
  -h, --help                Show this help

Behavior:
  - generates random admin/viewer passwords when not provided
  - writes a server-side bootstrap env file
  - writes a local observation env file
  - chmod 600 on both output files

Notes:
  - do not commit the generated files
  - copy the bootstrap file to the shared-dev server before running docker compose bootstrap
  - run from the repo root when using the follow-up commands below
EOF
}

bootstrap_out="${HOME}/.config/yuantus/bootstrap/shared-dev.bootstrap.env"
observation_out="${HOME}/.config/yuantus/p2-shared-dev.env"
base_url="https://<shared-dev-host>"
tenant_id="tenant-1"
org_id="org-1"
admin_username="admin"
viewer_username="ops-viewer"
admin_password=""
viewer_password=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --bootstrap-out)
      bootstrap_out="$2"
      shift 2
      ;;
    --observation-out)
      observation_out="$2"
      shift 2
      ;;
    --base-url)
      base_url="$2"
      shift 2
      ;;
    --tenant-id)
      tenant_id="$2"
      shift 2
      ;;
    --org-id)
      org_id="$2"
      shift 2
      ;;
    --admin-username)
      admin_username="$2"
      shift 2
      ;;
    --viewer-username)
      viewer_username="$2"
      shift 2
      ;;
    --admin-password)
      admin_password="$2"
      shift 2
      ;;
    --viewer-password)
      viewer_password="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

generate_password() {
  python3 - <<'PY'
import secrets
alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789-_"
print("".join(secrets.choice(alphabet) for _ in range(24)))
PY
}

if [[ -z "${admin_password}" ]]; then
  admin_password="$(generate_password)"
fi

if [[ -z "${viewer_password}" ]]; then
  viewer_password="$(generate_password)"
fi

mkdir -p "$(dirname "${bootstrap_out}")" "$(dirname "${observation_out}")"

cat > "${bootstrap_out}" <<EOF
# Generated by scripts/generate_p2_shared_dev_bootstrap_env.sh
# Contains real secrets. Do not commit.

YUANTUS_BOOTSTRAP_TENANT_ID=${tenant_id}
YUANTUS_BOOTSTRAP_ORG_ID=${org_id}

YUANTUS_BOOTSTRAP_ADMIN_USERNAME=${admin_username}
YUANTUS_BOOTSTRAP_ADMIN_PASSWORD=${admin_password}
YUANTUS_BOOTSTRAP_ADMIN_USER_ID=1
YUANTUS_BOOTSTRAP_ADMIN_ROLES=admin

YUANTUS_BOOTSTRAP_VIEWER_USERNAME=${viewer_username}
YUANTUS_BOOTSTRAP_VIEWER_PASSWORD=${viewer_password}
YUANTUS_BOOTSTRAP_VIEWER_USER_ID=2
YUANTUS_BOOTSTRAP_VIEWER_ROLES=ops-viewer

YUANTUS_BOOTSTRAP_SKIP_META=0
YUANTUS_BOOTSTRAP_DATASET_MODE=p2-observation
YUANTUS_BOOTSTRAP_FIXTURE_MANIFEST_PATH=./tmp/p2_observation_fixture_manifest.json
EOF

cat > "${observation_out}" <<EOF
BASE_URL="${base_url}"
USERNAME="${admin_username}"
PASSWORD="${admin_password}"
TENANT_ID="${tenant_id}"
ORG_ID="${org_id}"
ENVIRONMENT="shared-dev"
EOF

chmod 600 "${bootstrap_out}" "${observation_out}"

cat <<EOF
Generated shared-dev bootstrap material.

Bootstrap env:
  ${bootstrap_out}

Observation env:
  ${observation_out}

Bootstrap credentials:
  admin      -> ${admin_username} / ${admin_password}
  ops-viewer -> ${viewer_username} / ${viewer_password}

Next steps:
  1. From the repo root, validate the generated files:
       scripts/validate_p2_shared_dev_env.sh --mode both --bootstrap-env "${bootstrap_out}" --observation-env "${observation_out}"
  2. Copy bootstrap env to the server:
       cp "${bootstrap_out}" <server-repo>/deployments/docker/shared-dev.bootstrap.env
  3. On the server, from the repo root, run:
       docker compose --env-file ./deployments/docker/shared-dev.bootstrap.env --profile bootstrap run --rm bootstrap
       docker compose up -d api worker
  4. Locally, from the repo root, run:
       scripts/precheck_p2_observation_regression.sh --env-file "${observation_out}"
       OUTPUT_DIR="./tmp/p2-shared-dev-observation-\$(date +%Y%m%d-%H%M%S)" ARCHIVE_RESULT=1 scripts/run_p2_observation_regression.sh --env-file "${observation_out}"
EOF
