#!/usr/bin/env bash
# Strict gate report generator.
#
# Runs the strict gate steps and writes a single markdown report that can be
# committed as evidence ("regression evidence autopack").
#
# Usage:
#   scripts/strict_gate_report.sh
#   OUT_DIR=tmp/strict-gate scripts/strict_gate_report.sh
#   REPORT_PATH=docs/DAILY_REPORTS/STRICT_GATE_20260207.md scripts/strict_gate_report.sh
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

export PYTHONPATH="${PYTHONPATH:-src}"

timestamp="$(date +%Y%m%d-%H%M%S)"
run_id="${RUN_ID:-STRICT_GATE_${timestamp}}"

out_dir_default="${REPO_ROOT}/tmp/strict-gate/${run_id}"
OUT_DIR="${OUT_DIR:-$out_dir_default}"

report_default="${REPO_ROOT}/docs/DAILY_REPORTS/STRICT_GATE_${timestamp}.md"
REPORT_PATH="${REPORT_PATH:-$report_default}"

mkdir -p "$OUT_DIR"
mkdir -p "$(dirname "$REPORT_PATH")"

PYTEST_BIN="${PYTEST_BIN:-${REPO_ROOT}/.venv/bin/pytest}"
PLAYWRIGHT_CMD="${PLAYWRIGHT_CMD:-npx playwright test}"

if [[ ! -x "$PYTEST_BIN" ]]; then
  echo "ERROR: pytest not found at $PYTEST_BIN" >&2
  exit 2
fi

git_branch="$(git -C "$REPO_ROOT" branch --show-current 2>/dev/null || echo "")"
git_sha="$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo "")"
start_iso="$(date -Iseconds)"
start_epoch="$(date +%s)"

status_targeted="SKIP"
status_non_db="SKIP"
status_db="SKIP"
status_playwright="SKIP"

dur_targeted_s=0
dur_non_db_s=0
dur_db_s=0
dur_playwright_s=0

log_targeted="${OUT_DIR}/pytest_targeted.log"
log_non_db="${OUT_DIR}/pytest_non_db.log"
log_db="${OUT_DIR}/pytest_db.log"
log_playwright="${OUT_DIR}/playwright.log"

run_logged() {
  local name="$1"
  local log_path="$2"
  shift 2
  echo "==> ${name}"
  # shellcheck disable=SC2068
  ( "$@" ) >"$log_path" 2>&1
  return $?
}

step() {
  local name="$1"
  local log_path="$2"
  local status_var="$3"
  local dur_var="$4"
  shift 4

  local s e ec
  s="$(date +%s)"
  if run_logged "$name" "$log_path" "$@"; then
    ec=0
    printf -v "$status_var" "PASS"
  else
    ec=$?
    printf -v "$status_var" "FAIL(%s)" "$ec"
  fi
  e="$(date +%s)"
  printf -v "$dur_var" "%s" "$((e - s))"
}

if [[ -n "${TARGETED_PYTEST_ARGS:-}" ]]; then
  step "pytest (targeted)" "$log_targeted" status_targeted dur_targeted_s \
    "$PYTEST_BIN" -q ${TARGETED_PYTEST_ARGS}
else
  echo "==> pytest (targeted): SKIP (TARGETED_PYTEST_ARGS not set)"
fi

step "pytest (non-DB)" "$log_non_db" status_non_db dur_non_db_s \
  "$PYTEST_BIN" -q

step "pytest (DB)" "$log_db" status_db dur_db_s \
  env YUANTUS_PYTEST_DB=1 "$PYTEST_BIN" -q

step "playwright" "$log_playwright" status_playwright dur_playwright_s \
  bash -lc "$PLAYWRIGHT_CMD"

end_iso="$(date -Iseconds)"
end_epoch="$(date +%s)"
total_s="$((end_epoch - start_epoch))"

overall="PASS"
for s in "$status_targeted" "$status_non_db" "$status_db" "$status_playwright"; do
  if [[ "$s" == FAIL* ]]; then
    overall="FAIL"
    break
  fi
done

cat >"$REPORT_PATH" <<EOF
# Strict Gate Report

- Run ID: \`$run_id\`
- Started: \`$start_iso\`
- Ended: \`$end_iso\`
- Duration: \`${total_s}s\`
- Git: \`${git_branch}@${git_sha}\`

## Results

| Step | Status | Duration | Log |
| --- | --- | --- | --- |
| pytest (targeted) | $status_targeted | ${dur_targeted_s}s | \`$log_targeted\` |
| pytest (non-DB) | $status_non_db | ${dur_non_db_s}s | \`$log_non_db\` |
| pytest (DB) | $status_db | ${dur_db_s}s | \`$log_db\` |
| playwright | $status_playwright | ${dur_playwright_s}s | \`$log_playwright\` |

## Notes

- \`TARGETED_PYTEST_ARGS\`: \`${TARGETED_PYTEST_ARGS:-<unset>}\`
- \`PLAYWRIGHT_CMD\`: \`${PLAYWRIGHT_CMD}\`
- This report is generated by \`scripts/strict_gate_report.sh\`.
EOF

echo ""
echo "Report: $REPORT_PATH"
echo "Logs: $OUT_DIR"
echo "STRICT_GATE_REPORT: $overall"

if [[ "$overall" != "PASS" ]]; then
  exit 1
fi
